// Local language packs. Switching languages never requests generated translations.
import {language} from './catalog.mjs';
const keys=['programme','grade','subject','math','science','english','world-history','open','planned','unavailable','pilot','newLesson','start','pause','continue','next','repeat','send','mic','settings','full','title','answer','observe','solution','fact','correct','incorrect','review','missingVoice','testVoice','remote','volume','close','newConfirm','micConsent','micError','thinking','failed','followup','ready','ended','sample','pcNotice','reviewNotice','optional','common','return','voiceNote'];
const values={
 en:['GEM common programme','Grade / learning level','Subject','Mathematics','Science','English','World history','Open lesson','In preparation','Offered from Grade 7','Grade 2 mathematics · language pilot','New lesson','Start lesson','Pause','Continue','Next','Say it again','Send','Speak','Audio settings','Full screen','Addition within 20','Class answer or question','Observe','Check the solution','Remember','Yes.','Let us check the answer.','Review the explanation, then press Next.','No matching voice is available on this PC. Text remains available.','Test voice','Allow online browser voices','Volume','Close','Start a new lesson with different questions? Current progress will be replaced.','Browser speech recognition may send audio to its provider and needs permission. Have one classroom representative speak. GEM does not save recordings here. Continue?','Speech recognition unavailable. Please type instead.','Preparing an answer…','The additional answer was not retrieved. Your question is kept.','More questions? Continue returns to the lesson.','Choose a lesson. Language changes preserve your current progress.','Lesson complete','Existing English/French sample','PC-first trial. Additional-language mobile testing is not part of this stage.','New language translations are a trial and need a fluent teacher’s review. Voice availability is checked separately.','Optional local subjects · supplied when needed','Common content, independent of national school curricula','Back to course selection','Local voices are preferred. Online voices may send lesson text to their provider. No new paid speech service is connected.'],
 fr:['Programme commun GEM','Niveau d’apprentissage','Matière','Mathématiques','Sciences','Anglais','Histoire mondiale','Ouvrir la séance','En préparation','Proposé à partir du niveau 7','Mathématiques niveau 2 · essai linguistique','Nouvelle séance','Commencer','Pause','Continuer','Suivant','Répéter','Envoyer','Parler','Réglages audio','Plein écran','Additionner jusqu’à 20','Réponse ou question de la classe','Observer','Vérifier la solution','À retenir','Oui.','Vérifions la réponse.','Vérifiez l’explication, puis appuyez sur Suivant.','Aucune voix correspondante sur ce PC. Le texte reste disponible.','Tester la voix','Autoriser les voix en ligne du navigateur','Volume','Fermer','Commencer une nouvelle séance avec d’autres problèmes ? La progression actuelle sera remplacée.','La reconnaissance vocale peut envoyer l’audio à son fournisseur et demande une autorisation. Une seule personne parle pour la classe. GEM ne conserve pas d’enregistrement ici. Continuer ?','Reconnaissance vocale indisponible. Écrivez votre réponse.','Préparation d’une réponse…','La réponse supplémentaire n’a pas été obtenue. Votre question est conservée.','Une autre question ? Continuer reprend la leçon.','Choisissez une séance. Changer de langue conserve la progression.','Séance terminée','Exemple anglais/français existant','Essai destiné au PC. Les tests mobiles des autres langues ne font pas partie de cette étape.','Les nouvelles traductions sont à l’essai et doivent être relues par un enseignant qui maîtrise la langue. Les voix sont vérifiées séparément.','Matières locales facultatives · sur demande','Contenu commun, indépendant des programmes scolaires nationaux','Retour au choix de la séance','Les voix locales sont prioritaires. Les voix en ligne peuvent envoyer le texte au fournisseur. Aucun nouveau service vocal payant n’est connecté.'],
 ne:['GEM साझा पाठ्यक्रम','कक्षा / सिकाइ स्तर','विषय','गणित','विज्ञान','अङ्ग्रेजी','विश्व इतिहास','पाठ खोल्नुहोस्','तयारीमा','कक्षा ७ देखि उपलब्ध हुने','कक्षा २ गणित · भाषा परीक्षण','नयाँ पाठ','पाठ सुरु गर्नुहोस्','रोक्नुहोस्','जारी राख्नुहोस्','अर्को','फेरि भन्नुहोस्','पठाउनुहोस्','बोल्नुहोस्','आवाज सेटिङ','पूरा पर्दा','२० सम्म जोड','कक्षाको उत्तर वा प्रश्न','अवलोकन गर्नुहोस्','समाधान जाँच्नुहोस्','सम्झनुहोस्','हो।','उत्तर जाँचौँ।','व्याख्या जाँचेर अर्कोमा थिच्नुहोस्।','यो कम्प्युटरमा यस भाषाको आवाज भेटिएन। पाठ पढ्न सकिन्छ।','आवाज जाँच्नुहोस्','ब्राउजरको अनलाइन आवाज प्रयोग गर्न दिनुहोस्','आवाजको स्तर','बन्द गर्नुहोस्','फरक प्रश्नसहित नयाँ पाठ सुरु गर्ने? अहिलेको प्रगति बदलिनेछ।','आवाज पहिचान सेवाले आवाज आफ्नो सेवा प्रदायकलाई पठाउन सक्छ र अनुमति चाहिन्छ। कक्षाबाट एक जनाले मात्र बोल्नुहोस्। GEM ले यहाँ रेकर्डिङ राख्दैन। जारी राख्ने?','आवाज पहिचान उपलब्ध छैन। कृपया टाइप गर्नुहोस्।','उत्तर तयार हुँदै छ…','थप उत्तर प्राप्त भएन। तपाईंको प्रश्न राखिएको छ।','अर्को प्रश्न छ? पाठमा फर्कन जारी राख्नुहोस्।','पाठ छान्नुहोस्। भाषा बदल्दा अहिलेको प्रगति रहन्छ।','पाठ पूरा भयो','पहिलेकै अङ्ग्रेजी/फ्रान्सेली नमुना','यो परीक्षण कम्प्युटरका लागि हो। अन्य भाषाको मोबाइल परीक्षण यस चरणमा छैन।','नयाँ अनुवाद परीक्षणका लागि हुन्। भाषा जान्ने शिक्षकले जाँच्नुपर्छ। आवाजको उपलब्धता छुट्टै जाँचिन्छ।','स्थानीय वैकल्पिक विषय · आवश्यकताअनुसार','राष्ट्रिय विद्यालय पाठ्यक्रमबाट स्वतन्त्र साझा सामग्री','पाठ छनोटमा फर्कनुहोस्','कम्प्युटरको आवाजलाई प्राथमिकता दिइन्छ। अनलाइन आवाजले पाठ सेवा प्रदायकलाई पठाउन सक्छ। नयाँ सशुल्क आवाज सेवा जोडिएको छैन।'],
 ur:['GEM مشترکہ نصاب','جماعت / سیکھنے کی سطح','مضمون','ریاضی','سائنس','انگریزی','عالمی تاریخ','سبق کھولیں','تیاری جاری ہے','جماعت 7 سے پیش کیا جائے گا','جماعت 2 ریاضی · زبان کا آزمائشی سبق','نیا سبق','سبق شروع کریں','روکیں','جاری رکھیں','اگلا','دوبارہ کہیں','بھیجیں','بولیں','آواز کی ترتیبات','پوری اسکرین','20 تک جمع','جماعت کا جواب یا سوال','دیکھیں','حل کی جانچ کریں','یاد رکھیں','جی ہاں۔','آئیے جواب کی جانچ کریں۔','وضاحت دیکھیں، پھر اگلا دبائیں۔','اس کمپیوٹر پر اس زبان کی آواز دستیاب نہیں۔ متن پڑھا جا سکتا ہے۔','آواز آزمائیں','براؤزر کی آن لائن آوازوں کی اجازت دیں','آواز کی سطح','بند کریں','مختلف سوالات کے ساتھ نیا سبق شروع کریں؟ موجودہ پیش رفت بدل جائے گی۔','آواز کی شناخت کی خدمت آڈیو اپنے فراہم کنندہ کو بھیج سکتی ہے اور اجازت درکار ہے۔ جماعت کی طرف سے ایک شخص بولے۔ GEM یہاں ریکارڈنگ محفوظ نہیں کرتا۔ جاری رکھیں؟','آواز کی شناخت دستیاب نہیں۔ براہ کرم لکھیں۔','جواب تیار ہو رہا ہے…','اضافی جواب حاصل نہیں ہوا۔ آپ کا سوال محفوظ ہے۔','مزید سوال؟ سبق میں واپس جانے کے لیے جاری رکھیں دبائیں۔','سبق منتخب کریں۔ زبان بدلنے سے موجودہ پیش رفت برقرار رہتی ہے۔','سبق مکمل ہوا','موجودہ انگریزی/فرانسیسی نمونہ','یہ آزمائش کمپیوٹر کے لیے ہے۔ اس مرحلے میں دوسری زبانوں کی موبائل جانچ شامل نہیں۔','نئے تراجم آزمائشی ہیں۔ زبان جاننے والے استاد کی جانچ ضروری ہے۔ آواز کی دستیابی الگ جانچی جاتی ہے۔','مقامی اختیاری مضامین · ضرورت کے مطابق','قومی اسکولی نصاب سے آزاد مشترکہ مواد','سبق کے انتخاب پر واپس جائیں','مقامی آوازوں کو ترجیح دی جاتی ہے۔ آن لائن آواز متن فراہم کنندہ کو بھیج سکتی ہے۔ کوئی نئی بامعاوضہ آواز کی خدمت منسلک نہیں ہے۔'],
 sw:['Mtaala wa pamoja wa GEM','Darasa / kiwango cha kujifunza','Somo','Hisabati','Sayansi','Kiingereza','Historia ya dunia','Fungua somo','Inaandaliwa','Itatolewa kuanzia Darasa la 7','Hisabati Darasa la 2 · jaribio la lugha','Somo jipya','Anza somo','Sitisha','Endelea','Inayofuata','Sema tena','Tuma','Zungumza','Mipangilio ya sauti','Skrini nzima','Kujumlisha hadi 20','Jibu au swali la darasa','Chunguza','Hakiki suluhisho','Kumbuka','Ndiyo.','Tuhakiki jibu.','Hakiki maelezo, kisha bonyeza Inayofuata.','Hakuna sauti ya lugha hii kwenye kompyuta hii. Maandishi yanapatikana.','Jaribu sauti','Ruhusu sauti za mtandaoni za kivinjari','Kiwango cha sauti','Funga','Uanze somo jipya lenye maswali tofauti? Maendeleo ya sasa yatabadilishwa.','Utambuzi wa sauti unaweza kutuma sauti kwa mtoa huduma na unahitaji ruhusa. Mwakilishi mmoja wa darasa azungumze. GEM haihifadhi rekodi hapa. Uendelee?','Utambuzi wa sauti haupatikani. Tafadhali andika.','Jibu linaandaliwa…','Jibu la ziada halikupatikana. Swali lako limehifadhiwa.','Maswali mengine? Endelea hukurudisha kwenye somo.','Chagua somo. Kubadili lugha huhifadhi maendeleo ya sasa.','Somo limekamilika','Mfano uliopo wa Kiingereza/Kifaransa','Jaribio la kompyuta. Upimaji wa simu kwa lugha nyingine si sehemu ya hatua hii.','Tafsiri mpya ni za majaribio na zinahitaji kuhakikiwa na mwalimu anayejua lugha. Upatikanaji wa sauti unakaguliwa kando.','Masomo ya eneo ya hiari · yanapotakiwa','Maudhui ya pamoja, tofauti na mitaala ya kitaifa ya shule','Rudi kuchagua somo','Sauti za kompyuta zinapewa kipaumbele. Sauti za mtandaoni zinaweza kutuma maandishi kwa mtoa huduma. Hakuna huduma mpya ya sauti ya kulipia iliyounganishwa.']
};
for(const [lang,rows] of Object.entries(values))if(rows.length!==keys.length)throw Error('UI pack mismatch '+lang+': '+rows.length+'/'+keys.length);
export const UI=Object.fromEntries(Object.entries(values).map(([lang,v])=>[lang,Object.fromEntries(keys.map((k,i)=>[k,v[i]]))]));
const eq=(a,b,c)=>`${a} + ${b} = ${c}`;
export function text(lang,key){return UI[language(lang).code][key]||key;}
export function lessonText(s,lang,reveal=false){
 const a=s.a,b=s.b,n=s.missing?10-a:a+b,need=10-a,rest=b-need;
 const method=s.missing?'missing':s.id==='swap'?'swap':a<10&&a+b>10?'ten':b<=4||a===10?'count':'join';
 const formula=s.missing?eq(a,reveal?n:'?',10):eq(a,b,reveal?n:'?');
 const captions={
 en:{ob:s.missing?`The ten-frame has ${a} counters. How many more are needed to fill ten spaces?`:`Look at ${a} counters and ${b} more. How many are there altogether?`,fact:s.missing?'Count empty spaces to find the missing number.':'Moving the same counters does not change their total.',solve:s.missing?`There are ${n} empty spaces. Add ${n} counters to complete ten.`:method==='ten'?`${a} needs ${need} to make ten. Split ${b} into ${need} and ${rest}. Ten and ${rest} make ${n}.`:method==='swap'?`Swap the two groups. They are the same ${n} counters in a different order.`:method==='count'?`Start at ${a}. Count ${b} more steps: ${Array.from({length:b},(_,i)=>a+i+1).join(', ')}. The total is ${n}.`:`Join ${a} and ${b}. Count each counter once. There are ${n} altogether.`,hello:'Hello! Ask a question or share your thinking.',compare:'Addition joins amounts. For whole numbers, multiplication can count equal groups. Three groups of two can be written as two plus two plus two, which makes six.',recap:'In this lesson we practise adding within twenty, using counters, counting on and making ten. Your teacher can review the completed questions below.'},
 fr:{ob:s.missing?`Le cadre de dix contient ${a} jetons. Combien faut-il en ajouter pour remplir les dix cases ?`:`Regardez ${a} jetons et ${b} autres. Combien y en a-t-il en tout ?`,fact:s.missing?'Comptez les cases vides pour trouver le nombre manquant.':'Déplacer les mêmes jetons ne change pas leur nombre total.',solve:s.missing?`Il y a ${n} cases vides. Ajoutez ${n} jetons pour compléter dix.`:method==='ten'?`Il manque ${need} à ${a} pour faire dix. Partagez ${b} en ${need} et ${rest}. Dix et ${rest} font ${n}.`:method==='swap'?`Échangez la place des deux groupes. Ce sont les mêmes ${n} jetons dans un autre ordre.`:method==='count'?`Partez de ${a}. Comptez ${b} pas ajoutés : ${Array.from({length:b},(_,i)=>a+i+1).join(', ')}. Le total est ${n}.`:`Réunissez ${a} et ${b}. Comptez chaque jeton une seule fois. Il y en a ${n} en tout.`,hello:'Bonjour ! Posez une question ou expliquez votre raisonnement.',compare:'L’addition réunit des quantités. Pour les nombres entiers, la multiplication permet de compter des groupes égaux. Trois groupes de deux correspondent à deux plus deux plus deux, soit six.',recap:'Dans cette séance, nous travaillons les additions jusqu’à vingt avec des jetons, le comptage et les groupes de dix. L’enseignant peut revoir les questions terminées ci-dessous.'},
 ne:{ob:s.missing?`दश खाने ढाँचामा ${a} गोटी छन्। सबै दश खाना भर्न कति गोटी थप्नुपर्छ?`:`${a} गोटी र थप ${b} गोटी हेर्नुहोस्। जम्मा कति गोटी छन्?`,fact:s.missing?'खाली खाना गनेर छुटेको सङ्ख्या पत्ता लगाउनुहोस्।':'उही गोटी सार्दा तिनको जम्मा सङ्ख्या बदलिँदैन।',solve:s.missing?`${n} खाना खाली छन्। दश पूरा गर्न ${n} गोटी थप्नुहोस्।`:method==='ten'?`${a} लाई दश बनाउन ${need} चाहिन्छ। ${b} लाई ${need} र ${rest} मा छुट्याउनुहोस्। दश र ${rest} जोड्दा ${n} हुन्छ।`:method==='swap'?`दुई समूहको ठाउँ साट्नुहोस्। क्रम फरक भए पनि उही ${n} गोटी छन्।`:method==='count'?`${a} बाट सुरु गर्नुहोस्। थप ${b} पटक गन्नुहोस्: ${Array.from({length:b},(_,i)=>a+i+1).join(', ')}। जम्मा ${n} हुन्छ।`:`${a} र ${b} लाई एकै ठाउँमा राख्नुहोस्। हरेक गोटी एक पटक गन्नुहोस्। जम्मा ${n} गोटी छन्।`,hello:'नमस्ते! प्रश्न सोध्नुहोस् वा आफ्नो सोच बताउनुहोस्।',compare:'जोडले परिमाणहरू एकै ठाउँमा राख्छ। पूर्ण सङ्ख्यामा गुणनले बराबर आकारका समूह गन्न मद्दत गर्छ। दुई दुईवटा भएका तीन समूहमा दुई जोड दुई जोड दुई हुन्छ, अर्थात् छ।',recap:'यस पाठमा हामी गोटी, अगाडि गन्ने तरिका र दश बनाउने तरिका प्रयोग गरेर बीससम्म जोडको अभ्यास गर्छौँ। शिक्षकले तल पूरा भएका प्रश्नहरू हेर्न सक्नुहुन्छ।'},
 ur:{ob:s.missing?`دس خانوں کے سانچے میں ${a} گنتی کے ٹکڑے ہیں۔ دس خانے بھرنے کے لیے کتنے ٹکڑے اور چاہییں؟`:`${a} ٹکڑے اور مزید ${b} ٹکڑے دیکھیں۔ کل کتنے ٹکڑے ہیں؟`,fact:s.missing?'خالی خانے گن کر نامعلوم عدد معلوم کریں۔':'انہی ٹکڑوں کی جگہ بدلنے سے ان کی کل تعداد نہیں بدلتی۔',solve:s.missing?`${n} خانے خالی ہیں۔ دس پورے کرنے کے لیے ${n} ٹکڑے شامل کریں۔`:method==='ten'?`${a} کو دس بنانے کے لیے ${need} چاہیے۔ ${b} کو ${need} اور ${rest} میں بانٹیں۔ دس اور ${rest} مل کر ${n} ہوتے ہیں۔`:method==='swap'?`دونوں گروہوں کی جگہ بدلیں۔ ترتیب مختلف ہے، لیکن ٹکڑے وہی ${n} ہیں۔`:method==='count'?`${a} سے شروع کریں۔ مزید ${b} قدم گنیں: ${Array.from({length:b},(_,i)=>a+i+1).join('، ')}۔ کل ${n} ہوتے ہیں۔`:`${a} اور ${b} کو اکٹھا کریں۔ ہر ٹکڑا ایک بار گنیں۔ کل ${n} ٹکڑے ہیں۔`,hello:'ہیلو! سوال پوچھیں یا اپنی سوچ بیان کریں۔',compare:'جمع میں مقداروں کو اکٹھا کیا جاتا ہے۔ صحیح اعداد میں ضرب برابر سائز کے گروہوں کی گنتی کر سکتی ہے۔ دو دو چیزوں کے تین گروہ، دو جمع دو جمع دو ہیں، یعنی چھ۔',recap:'اس سبق میں ہم گنتی کے ٹکڑوں، آگے گننے اور دس بنانے کی مدد سے بیس تک جمع کی مشق کرتے ہیں۔ استاد نیچے مکمل کیے گئے سوالات دیکھ سکتا ہے۔'},
 sw:{ob:s.missing?`Fremu ya nafasi kumi ina vihesabio ${a}. Tunahitaji kuongeza vingapi ili kujaza nafasi zote kumi?`:`Angalia vihesabio ${a} na vingine ${b}. Kuna vingapi kwa jumla?`,fact:s.missing?'Hesabu nafasi tupu kupata namba inayokosekana.':'Kuhamisha vihesabio vilevile hakubadili jumla yake.',solve:s.missing?`Kuna nafasi ${n} tupu. Ongeza vihesabio ${n} kutimiza kumi.`:method==='ten'?`${a} inahitaji ${need} kufikia kumi. Gawa ${b} kuwa ${need} na ${rest}. Kumi na ${rest} ni ${n}.`:method==='swap'?`Badilisha nafasi za makundi mawili. Bado kuna vihesabio vilevile ${n} katika mpangilio tofauti.`:method==='count'?`Anza na ${a}. Hesabu hatua ${b} zaidi: ${Array.from({length:b},(_,i)=>a+i+1).join(', ')}. Jumla ni ${n}.`:`Unganisha ${a} na ${b}. Hesabu kila kihesabio mara moja. Kuna ${n} kwa jumla.`,hello:'Habari! Uliza swali au eleza ulivyofikiri.',compare:'Kujumlisha huunganisha kiasi. Kwa namba nzima, kuzidisha kunaweza kuhesabu makundi yenye idadi sawa. Makundi matatu ya vitu viwili ni mbili pamoja na mbili pamoja na mbili, jumla sita.',recap:'Katika somo hili tunafanya mazoezi ya kujumlisha hadi ishirini kwa vihesabio, kuhesabu kuendelea na kutengeneza kumi. Mwalimu anaweza kupitia maswali yaliyokamilika hapa chini.'}
 };
 return {...captions[language(lang).code],formula,answer:n,method};
}
export function answerNumber(value){
 let q=String(value).trim().toLowerCase().replace(/[.!?۔।]+$/,'').replace(/[०-९]/g,c=>String(c.charCodeAt(0)-0x0966)).replace(/[۰-۹]/g,c=>String(c.charCodeAt(0)-0x06f0)).replace(/[٠-٩]/g,c=>String(c.charCodeAt(0)-0x0660));
 q=q.replace(/^(?:the answer is|it is|it's|la réponse est|c'est|उत्तर|جواب|jibu ni)\s*[:：]?\s*/u,'');
 if(/^\d{1,2}$/.test(q))return Number(q);
 const lists=[['zero','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen','twenty'],['zéro','un','deux','trois','quatre','cinq','six','sept','huit','neuf','dix','onze','douze','treize','quatorze','quinze','seize','dix-sept','dix-huit','dix-neuf','vingt'],['शून्य','एक','दुई','तीन','चार','पाँच','छ','सात','आठ','नौ','दश','एघार','बाह्र','तेह्र','चौध','पन्ध्र','सोह्र','सत्र','अठार','उन्नाइस','बीस'],['صفر','ایک','دو','تین','چار','پانچ','چھ','سات','آٹھ','نو','دس','گیارہ','بارہ','تیرہ','چودہ','پندرہ','سولہ','سترہ','اٹھارہ','انیس','بیس'],['sifuri','moja','mbili','tatu','nne','tano','sita','saba','nane','tisa','kumi','kumi na moja','kumi na mbili','kumi na tatu','kumi na nne','kumi na tano','kumi na sita','kumi na saba','kumi na nane','kumi na tisa','ishirini']];
 for(const row of lists){const n=row.indexOf(q);if(n>=0)return n;}return null;
}
