import fs from 'node:fs/promises';import http from 'node:http';import path from 'node:path';import assert from 'node:assert/strict';import {chromium as playwright}from 'playwright-core';import chromium from '@sparticuz/chromium';
const root=path.resolve('mission-dist'),checks=[],errors=[];const server=http.createServer(async(req,res)=>{try{let pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(pathname==='/')pathname='/index.html';const f=path.resolve(root,'.'+pathname);if(!f.startsWith(root+path.sep))throw Error('Bad path');const body=await fs.readFile(f);const type=f.endsWith('.html')?'text/html':/\.(mjs|js)$/.test(f)?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.png')?'image/png':f.endsWith('.json')?'application/json':'application/octet-stream';res.writeHead(200,{'Content-Type':type});res.end(body);}catch{res.writeHead(404);res.end('Not found');}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;let browser;
try{
 browser=await playwright.launch({args:[...chromium.args,'--enable-unsafe-swiftshader'],executablePath:await chromium.executablePath(),headless:true});const context=await browser.newContext({viewport:{width:1366,height:768}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));let modelRequests=0;page.on('request',req=>{if(req.url().includes('avatar-sample-z.vrm'))modelRequests++;assert.ok(req.url().startsWith(url)||req.url().startsWith('data:')||req.url().startsWith('blob:'),'Unexpected external browser request');});await page.goto(url);await page.click('#load-avatar');await page.waitForFunction(()=>window.GEM_PILOT?.modelReady,{},{timeout:90000});await page.waitForFunction(()=>window.GEM_PILOT.modelStats.frames>0,{},{timeout:15000});let s=await page.evaluate(()=>window.GEM_PILOT);assert.ok(s.modelStats.renderCalls>0);assert.ok(s.modelStats.triangles>0);checks.push('Original VRM loaded and real WebGL geometry rendered; animation frames advance.');
 await page.evaluate(()=>dispatchEvent(new CustomEvent('gem-avatar-speaking',{detail:{speaking:true}})));await page.waitForFunction(()=>window.GEM_PILOT.modelStats.mouth>0,{},{timeout:15000});await page.evaluate(()=>dispatchEvent(new CustomEvent('gem-avatar-speaking',{detail:{speaking:false}})));await page.waitForFunction(()=>window.GEM_PILOT.modelStats.mouth===0,{},{timeout:15000});checks.push('Mouth responds to speech-state signals; idle returns to closed mouth. This is not a hardware audio test.');
 await page.click('#play');await page.click('#next');await page.fill('#answer','7');await page.click('#answer-form button[type=submit]');assert.equal(await page.locator('#equation').innerText(),'4 + 3 = 7');const before=await page.evaluate(()=>window.GEM_PILOT);await page.click('[data-lang=fr]');s=await page.evaluate(()=>window.GEM_PILOT);assert.equal(s.index,before.index);assert.equal(s.reveal,true);assert.ok(s.elapsed>=before.elapsed);assert.equal(await page.locator('#equation').innerText(),'4 + 3 = 7');checks.push('EN to FR preserves step, revealed answer and elapsed time.');
 for(let i=0;i<3;i++)await page.click('#next');await page.fill('#answer','14');await page.click('#answer-form button[type=submit]');assert.equal(await page.locator('#equation').innerText(),'8 + 7 = ?');await page.fill('#answer','quinze');await page.click('#answer-form button[type=submit]');assert.equal(await page.locator('#equation').innerText(),'8 + 7 = 15');await page.fill('#answer','Pourquoi faire dix ?');await page.click('#answer-form button[type=submit]');assert.ok((await page.locator('#feedback').innerText()).includes('Dix'));assert.equal((await page.evaluate(()=>window.GEM_PILOT)).index,4);checks.push('Wrong answer receives a scaffold, French answer succeeds, prepared Q&A stays on the same step.');
 await page.click('#play');const paused=await page.evaluate(()=>window.GEM_PILOT.elapsed);await page.waitForTimeout(600);assert.equal(await page.evaluate(()=>window.GEM_PILOT.elapsed),paused);checks.push('Pause freezes the lesson timer.');
 await fs.mkdir(root+'/checks',{recursive:true});for(const [name,width,height]of [['tv',1920,1080],['desktop',1366,768],['phone-portrait',390,844],['phone-landscape',844,390],['small-phone',360,640]]){await page.setViewportSize({width,height});await page.waitForTimeout(300);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),name+' overflow');assert.ok(await page.locator('#avatar').evaluate(e=>e.clientWidth>0&&e.clientHeight>0));for(const id of ['play','next','mic'])assert.ok((await page.locator('#'+id).boundingBox()).height>=43.5);await page.screenshot({path:root+'/checks/'+name+'.png',fullPage:true});}checks.push('Five viewport sizes: no horizontal overflow; visible real canvas and >=44px core controls.');
 await page.setViewportSize({width:1366,height:768});await page.click('[data-view=teacher]');assert.equal(await page.locator('.board').isVisible(),false);await page.click('[data-view=board]');assert.equal(await page.locator('#stage').isVisible(),false);await page.click('[data-view=both]');assert.equal(await page.locator('#stage').isVisible(),true);checks.push('Teacher-only, board-only and split views restore correctly.');
 await page.click('#settings-open');await page.click('#prepare');await page.waitForFunction(()=>document.getElementById('storage-status').textContent.length>0);await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.click('#settings-close');await page.reload();await page.click('#load-avatar');await page.waitForFunction(()=>window.GEM_PILOT?.modelReady,{},{timeout:60000});s=await page.evaluate(()=>window.GEM_PILOT);assert.ok(s.modelStats.cached);assert.equal(s.index,4);assert.ok(s.paused);checks.push('Reload restores paused progress; existing VRM loaded from local cache.');
 await context.setOffline(true);await page.reload();await page.click('#load-avatar');await page.waitForFunction(()=>window.GEM_PILOT?.modelReady,{},{timeout:60000});assert.ok((await page.evaluate(()=>window.GEM_PILOT)).modelStats.cached);checks.push('Prepared page and original 3D teacher reload without network. Online voices/microphone are not covered.');assert.equal(modelRequests,1);assert.deepEqual(errors,[]);checks.push('No uncaught page errors; no paid API calls; original VRM fetched once.');
 await fs.writeFile(root+'/test-report.json',JSON.stringify({status:'PASS',buildTime:new Date().toISOString(),checks,modelRequests,paidApiRequests:0,limitations:['No physical speaker/microphone test','No real iPhone/Android/TV test','No generative AI integration','Original model metadata permission review required before public release']},null,2));console.log('BROWSER PASS',JSON.stringify(checks));
}catch(error){console.error('BROWSER FAIL',error,errors);throw error;}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}
