// Country identity and teaching language are independent. No unverified national alignment.
export const countries=[['gem','GEM common pilot','Pilote commun GEM'],['CD','DR Congo','RD Congo'],['CG','Republic of the Congo','République du Congo'],['NG','Nigeria','Nigeria'],['SD','Sudan','Soudan'],['SS','South Sudan','Soudan du Sud'],['KE','Kenya','Kenya'],['UG','Uganda','Ouganda'],['TZ','Tanzania','Tanzanie'],['RW','Rwanda','Rwanda'],['CM','Cameroon','Cameroun'],['SN','Senegal','Sénégal'],['CI','Côte d’Ivoire','Côte d’Ivoire'],['GH','Ghana','Ghana'],['ZA','South Africa','Afrique du Sud'],['ET','Ethiopia','Éthiopie'],['other','Other country · not yet mapped','Autre pays · programme à préparer']];
export const subjects=[['math','Mathematics','Mathématiques'],['language','Language & literacy','Langue et lecture'],['science','Science','Sciences'],['social','Social studies','Sciences humaines'],['history','History','Histoire'],['geography','Geography','Géographie'],['civics','Civics & character','Éducation civique et morale'],['arts','Arts','Arts'],['music','Music','Musique'],['pe','Physical education','Éducation physique'],['computing','Computing','Informatique']];
export const defaultSelection={country:'gem',grade:2,subject:'math',minutes:40,classSize:25};
export function normalizeSelection(value={}){return {country:countries.some(c=>c[0]===value.country)?value.country:'gem',grade:Number.isInteger(Number(value.grade))&&Number(value.grade)>=1&&Number(value.grade)<=12?Number(value.grade):2,subject:subjects.some(s=>s[0]===value.subject)?value.subject:'math',minutes:Number.isInteger(Number(value.minutes))&&Number(value.minutes)>=5&&Number(value.minutes)<=180?Number(value.minutes):40,classSize:Number.isInteger(Number(value.classSize))&&Number(value.classSize)>=20&&Number(value.classSize)<=30?Number(value.classSize):25};}
export const lessonAvailable=s=>s.country==='gem'&&s.grade===2&&s.subject==='math';
export const CONTENT_POLICY={id:'gem-reformed-group-v1',basis:'GEM Reformed Christian education',excluded:['evolution','natural selection','common ancestry','Darwin','human evolution'],advancedCourses:false,reviewRequired:true};
// Scope gate for this prepared pilot. Future generative lessons require a separate reviewed pipeline.
export const excludedTopic=text=>/\b(?:evolution(?:ary)?|évolution|evolut(?:ion|if|ive)|natural selection|sélection naturelle|selection naturelle|common ancestr\w*|anc[êe]tre[s]? commun[s]?|darwin\w*|human evolution)\b|진화|자연\s*선택|공통\s*조상|다윈|인류\s*진화/i.test(String(text).normalize('NFD').replace(/[\u0300-\u036f]/g,'').normalize('NFC'));
