// One transactional path for typed and recognized answers. No input is discarded silently.
import {makeSession,validateSession,activateSession,VERSION} from './reliable-lessons.mjs';
import {classify,localReply,solution,safeArithmeticText,numeral,clean} from './tutor-core.mjs';
import {excludedTopic} from './classroom-catalog.mjs';
const SESSION='gem-g2-reliable-session-v1', HISTORY='gem-g2-recent-starts-v1';
export function createLessonSupport(h,ui){
 const $=id=>document.getElementById(id), state=()=>h.state(), fr=()=>state().lang==='fr';
 let session,busy=false,request=null,epoch=0,lastReply=null,review=false,unresolved=false,holdUntil=0,history=[],provider='not-tested',requests=0,accepted=0,answered=0,lastSource='',lastOutcome='',statusMode='ready';
 const banner=document.createElement('p');banner.id='lesson-service-status';banner.setAttribute('role','status');document.querySelector('.interaction').append(banner);
 const receipt=document.createElement('p');receipt.id='answer-receipt';receipt.setAttribute('role','status');document.querySelector('#answer-form').after(receipt);
 const fresh=document.createElement('button');fresh.id='group-new-lesson';fresh.type='button';document.querySelector('.header-tools').prepend(fresh);
 const style=document.createElement('style');style.textContent='#group-new-lesson{min-height:44px}#feedback{white-space:pre-wrap}#answer-receipt,#lesson-service-status{font-size:13px;line-height:1.6;overflow-wrap:anywhere;margin:8px 0;color:#385951}#answer-receipt:not(:empty){padding:9px 12px;background:#e4f3ea;border-left:4px solid #126d59}';document.head.append(style);
 function status(mode){statusMode=mode||'ready'; const labels={ready:['Questions are welcome at every step. Calculations and greetings work locally.','Vous pouvez poser une question à chaque étape. Calculs et salutations fonctionnent sur cet appareil.'],pending:['Your question was received. Preparing an additional answer…','Votre question a été reçue. Préparation d’une réponse supplémentaire…'],failed:['Your question was received, but the additional answer is unavailable. Your text is kept. Try again or type “Explain again”.','Votre question a été reçue, mais la réponse supplémentaire est indisponible. Le texte est conservé. Réessayez ou écrivez « Explique encore ».'],connected:['Additional answer received. Your teacher can check the explanation.','Réponse supplémentaire reçue. L’enseignant peut vérifier l’explication.'],resume:['Previous lesson position restored, paused. Press Continue to resume.','Position précédente restaurée, en pause. Appuyez sur Continuer pour reprendre.']};banner.textContent=(labels[statusMode]||labels.ready)[fr()?1:0];}
 function persist(){if(!session)return;try{localStorage.setItem(SESSION,JSON.stringify({...session,review,unresolved,lastReply,progress:{index:state().index,started:state().started,ended:state().ended,reveal:state().reveal,finishReason:state().finishReason||''}}));}catch{}}
 function cancel(){epoch++;request?.abort();request=null;busy=false;}
 function viewKey(){const s=h.current();return `${session.id}:${s.id}:${s.a}:${s.b}:${state().lang}`;}
 function reset(){cancel();let recent=[];try{recent=JSON.parse(localStorage.getItem(HISTORY))||[];if(!Array.isArray(recent))recent=[];}catch{}session=makeSession(recent);h.steps.splice(0,h.steps.length,...session.steps);activateSession(h.steps);review=false;unresolved=false;lastReply=null;history=[];holdUntil=0;Object.assign(state(),{index:1,elapsed:0,stepElapsed:0,started:false,paused:true,ended:false,reveal:false,waiting:true,finishReason:''});h.clearResult();$('answer').value='';receipt.textContent='';ui.setExplain();try{localStorage.setItem(HISTORY,JSON.stringify([...recent,session.first].slice(-12)));}catch{}persist();}
 function restore(){let saved;try{saved=JSON.parse(localStorage.getItem(SESSION));}catch{}if(!validateSession(saved)){reset();return;}session=saved;h.steps.splice(0,h.steps.length,...session.steps);activateSession(h.steps);const p=saved.progress;if(!p||!Number.isInteger(p.index)||p.index<0||p.index>=h.steps.length){reset();return;}Object.assign(state(),{index:Math.max(1,p.index),started:!!p.started,ended:!!p.ended,reveal:p.index===0?false:!!p.reveal,paused:true,finishReason:p.finishReason||''});review=!!saved.review;unresolved=false;if(saved.lastReply&&typeof saved.lastReply.reply==='string'&&saved.lastReply.reply.length<1800&&saved.lastReply.key===viewKey())lastReply=saved.lastReply;
 // Migrate the old unconfirmed Start/End toggle's prematurely ended state.
 if(state().ended&&state().index<h.steps.length-1&&!state().finishReason){state().ended=false;state().started=true;status('resume');}persist();}
 function onStep(){cancel();lastReply=null;review=false;unresolved=false;holdUntil=0;receipt.textContent='';persist();}
 function beforeAdvance(){if(busy)return false;if(review&&h.mediaState().busy)return false;review=false;unresolved=false;lastReply=null;holdUntil=0;persist();return true;}
 function ensureInteractive(){const s=state();if(s.index===0){s.index=1;s.reveal=false;ui.setExplain();}if(!s.started||s.ended){s.started=true;s.ended=false;s.paused=true;s.finishReason='';}return s;}
 function interpretTurn(question,s){
  const q=clean(question),hello=/^(?:hello|hi|hey|bonjour|salut|bonsoir|안녕하세요|안녕)(?:[ ,!]+(?:teacher|professor|professeur|ma[iî]tre|선생님))?[!. ]*$/.test(q),thanks=/^(?:thank you|thanks|merci|감사합니다)(?:[ ,]+teacher)?[!. ]*$/.test(q);
  if(hello||thanks)return {kind:'greeting'};
  if(/^(?:can (?:i|we) use (?:my |our )?(?:fingers|counters)|may (?:i|we) use (?:my |our )?fingers|can (?:i|we) check (?:this|it) using (?:my |our )?fingers|(?:puis-je|peut-on|pouvons-nous).*(?:doigts|jetons))\??$/.test(q))return {kind:'fingers'};
  if(/^(?:explain(?: again)?(?: please)?|please explain(?: again)?|explain (?:this|it|that|the answer)(?: again)?|explique(?:z)?(?: encore)?|reexplique(?:z)?|again|repeat|encore|i (?:don't|do not) understand|je ne comprends pas|설명해 주세요|다시 설명해 주세요|모르겠습니다)[.!? ]*$/.test(q))return {kind:'explain'};
  const stripped=q.replace(/^(?:the answer is|it is|it's|c'est|la reponse est)\s*/,'').replace(/\s+(?:counters|objects|pencils|books|jetons|objets|crayons|livres)[.!?]?$/,'');const n=numeral(stripped);if(n!==null&&s.answer!==null)return {kind:n===solution(s)?'correct':'incorrect',n};
  const r=classify(question,s);
  // An arbitrary question containing "explain" is not a command to recite a fixed answer.
  if(r.kind==='explain'&&/\b(?:explain|explique|expliquez)\b/.test(q)&&q.length>35)return {kind:'question'};
  return r;
 }
 function replyFor(result,s,lang){if(result.kind==='fingers')return lang==='fr'?`Oui. Vous pouvez utiliser vos doigts ou des jetons. Gardez ${s.a} comme point de départ, puis comptez ${s.b} pas ajoutés. Écrivez ensuite votre réponse.`:`Yes. You can use fingers or counters. Keep ${s.a} as your starting number, then count ${s.b} extra steps. Enter your answer when you are ready.`;return localReply(result,s,lang);}
 function receive(result,reply){lastReply={key:viewKey(),result,reply,lang:state().lang};if(['incorrect','correct','explain'].includes(result.kind)){state().reveal=true;state().waiting=false;ui.answered();}review=result.kind==='incorrect'||(review&&result.kind!=='correct');unresolved=result.kind==='clarify';holdUntil=performance.now()+10000;answered++;lastOutcome=result.kind;ui.refresh();$('feedback').hidden=false;$('feedback').textContent=reply;$('caption').textContent=reply;if(!document.hidden)h.speak(reply,true);persist();}
 async function submit(event,source='text'){
  event?.preventDefault();const question=$('answer').value.trim();if(!question){receipt.textContent=fr()?'Écrivez ou dites une réponse, puis envoyez-la.':'Type or say an answer, then send it.';return;}
  ensureInteractive();ui.stop();cancel();accepted++;lastSource=source;receipt.textContent=(fr()?'Reçu : ':'Received: ')+question;status('ready');const key=viewKey(),s=h.current(),lang=state().lang,generation=epoch;let result=interpretTurn(question,s),reply;
  if(excludedTopic(question)){result={kind:'clarify'};reply=lang==='fr'?'Restons sur la question de mathématiques affichée. Que souhaitez-vous revoir ?':'Let’s stay with the mathematics question on the board. What would you like to review?';}else reply=replyFor(result,s,lang);
  if(reply){receive(result,reply);history.push({question,answer:reply});history=history.slice(-4);if($('answer').value.trim()===question)$('answer').value='';return;}
  busy=true;unresolved=true;lastReply=null;ui.refresh();status('pending');request=new AbortController();const controller=request,timer=setTimeout(()=>controller.abort(),22000);requests++;
  try{const res=await fetch('/api/mission-chat',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({question,lang,step:{a:s.a,b:s.b,missing:s.missing===true},phase:ui.phase(),visibleExplanation:ui.phaseText().slice(0,1000),history})});const data=await res.json().catch(()=>({}));if(generation!==epoch||key!==viewKey()||state().ended)return;if(!res.ok||typeof data.answer!=='string'||!safeArithmeticText(data.answer)||data.targetAnswer!==solution(s))throw Error(data.code||'connection');busy=false;request=null;provider=data.source==='openai'?'connected':'local';receive({kind:data.scope==='clarify'?'clarify':'ai'},data.answer);history.push({question,answer:data.answer});history=history.slice(-4);if($('answer').value.trim()===question)$('answer').value='';status('connected');}
  catch(error){if(generation!==epoch||key!==viewKey()||state().ended)return;busy=false;request=null;provider=error.message==='not_configured'?'not-configured':'temporarily-unavailable';unresolved=true;lastOutcome='service-unavailable';status('failed');ui.refresh();}
  finally{clearTimeout(timer);if(generation===epoch){busy=false;request=null;ui.refresh();}}
 }
 function render(){fresh.textContent=fr()?'↻ Nouvelle séance':'↻ New lesson';if(lastReply&&lastReply.key!==viewKey()){const reply=lastReply.result.kind!=='ai'?replyFor(lastReply.result,h.current(),state().lang):null;lastReply=reply?{...lastReply,key:viewKey(),reply,lang:state().lang}:null;}if(lastReply){$('feedback').hidden=false;$('feedback').textContent=lastReply.reply;$('caption').textContent=lastReply.reply;}if(busy)$('group-advance').disabled=true;if(review)$('group-advance').textContent=fr()?'Compris · Suivant →':'Reviewed · Next →';persist();}
 fresh.onclick=()=>{if(state().started&&!state().ended&&!confirm(fr()?'Commencer une nouvelle séance avec d’autres problèmes ?':'Start a new lesson with different questions?'))return;ui.stop();reset();ui.refresh();status('ready');};restore();if(statusMode==='ready')status('ready');
 Object.defineProperty(window,'GEM_RELIABILITY',{get:()=>({version:'input-v2',sessionId:session?.id,first:session?.first,step:{id:h.current().id,a:h.current().a,b:h.current().b,missing:!!h.current().missing,answer:h.current().answer},busy,reviewRequired:review,unresolved,provider,aiRequests:requests,accepted,answered,lastSource,lastOutcome})});
 return {render,submit,cancel,onStep,reset,ensureInteractive,ensureFresh:()=>{if(state().ended)reset();},beforeAdvance,hold:()=>busy||review||unresolved||performance.now()<holdUntil,waitingMessage:()=>fr()?(busy?'Réponse en cours…':review?'Lisez la correction, puis appuyez sur Suivant.':unresolved?'Question conservée · vous pouvez préciser votre demande.':'Temps pour lire la réponse.'):(busy?'Preparing an answer…':review?'Read the correction, then press Next.':unresolved?'Question preserved · you may clarify your request.':'Time to read the answer.'),busy:()=>busy};
}
