import {makeSession,validateSession,activateSession,VERSION} from './reliable-lessons.mjs';
import {classify,localReply,solution,safeArithmeticText} from './tutor-core.mjs';
import {excludedTopic} from './classroom-catalog.mjs';
const SESSION='gem-g2-reliable-session-v1',HISTORY='gem-g2-recent-starts-v1';
export function createLessonSupport(h,ui){
 const $=id=>document.getElementById(id),state=()=>h.state();let session,busy=false,request=null,epoch=0,lastReply=null,review=false,unresolved=false,holdUntil=0,history=[],provider='not-tested',requests=0;
 const banner=document.createElement('p');banner.id='lesson-service-status';banner.setAttribute('role','status');banner.style.cssText='font-size:12px;line-height:1.55;margin:8px 0;color:#385951;';document.querySelector('.interaction').append(banner);
 const fresh=document.createElement('button');fresh.id='group-new-lesson';fresh.type='button';document.querySelector('.header-tools').prepend(fresh);
 const style=document.createElement('style');style.textContent='#group-new-lesson{min-height:44px}#feedback{white-space:pre-wrap}#lesson-service-status{overflow-wrap:anywhere}';document.head.append(style);
 function status(message){banner.textContent=message||(state().lang==='fr'?'Calcul et explications locales · Questions supplémentaires : IA à la demande, avec internet. Ne saisissez pas de données personnelles.':'Local calculations and explanations · Additional questions use AI on demand with internet. Do not enter personal information.');}
 function persist(){if(!session)return;try{localStorage.setItem(SESSION,JSON.stringify({...session,review,unresolved,progress:{index:state().index,started:state().started,ended:state().ended,reveal:state().reveal}}));}catch{}}
 function reset(){cancel();let recent=[];try{recent=JSON.parse(localStorage.getItem(HISTORY))||[];if(!Array.isArray(recent))recent=[];}catch{}session=makeSession(recent);h.steps.splice(0,h.steps.length,...session.steps);activateSession(h.steps);review=false;unresolved=false;lastReply=null;history=[];holdUntil=0;Object.assign(state(),{index:0,elapsed:0,stepElapsed:0,started:false,paused:true,ended:false,reveal:false,waiting:true});h.clearResult();$('answer').value='';ui.setExplain();try{localStorage.setItem(HISTORY,JSON.stringify([...recent,session.first].slice(-12)));}catch{}persist();}
 function restore(){let saved;try{saved=JSON.parse(localStorage.getItem(SESSION));}catch{}if(validateSession(saved)){session=saved;h.steps.splice(0,h.steps.length,...session.steps);activateSession(h.steps);review=!!saved.review;unresolved=!!saved.unresolved;const p=saved.progress;if(p&&Number.isInteger(p.index)&&p.index>=0&&p.index<h.steps.length)Object.assign(state(),{index:p.index,started:!!p.started,ended:!!p.ended,reveal:!!p.reveal,paused:true});else reset();}else reset();}
 function cancel(){epoch++;request?.abort();request=null;busy=false;}
 function viewKey(){const s=h.current();return `${session.id}:${s.id}:${s.a}:${s.b}:${state().lang}`;}
 function onStep(){cancel();lastReply=null;review=false;unresolved=false;holdUntil=0;persist();}
 function beforeAdvance(){if(busy||h.mediaState().busy)return false;review=false;unresolved=false;lastReply=null;holdUntil=0;persist();return true;}
 function receive(result,reply){lastReply={key:viewKey(),result,reply,lang:state().lang};if(['incorrect','correct','explain'].includes(result.kind)){state().reveal=true;state().waiting=false;ui.answered();}review=result.kind==='incorrect';unresolved=result.kind==='clarify';holdUntil=performance.now()+10000;ui.refresh();$('feedback').hidden=false;$('feedback').textContent=reply;$('caption').textContent=reply;h.speak(reply,true);persist();}
 async function submit(event){event?.preventDefault();if(busy||!state().started||state().ended)return;const question=$('answer').value.trim();if(!question)return;ui.stop();cancel();const key=viewKey(),s=h.current(),lang=state().lang,generation=epoch;let result=classify(question,s),reply;if(excludedTopic(question)){result={kind:'clarify'};reply=lang==='fr'?'Revenons aux mathématiques. Quelle partie du calcul souhaitez-vous revoir ?':'Let’s return to mathematics. Which part of the calculation would you like to review?';}else reply=localReply(result,s,lang);
 if(reply){receive(result,reply);history.push({question,answer:reply});history=history.slice(-4);$('answer').value='';return;}
 busy=true;unresolved=true;lastReply=null;ui.refresh();status(lang==='fr'?'Je prépare une explication de votre question…':'Preparing an explanation of your question…');request=new AbortController();const controller=request,timer=setTimeout(()=>controller.abort(),22000);requests++;
 try{const res=await fetch('/api/mission-chat',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({question,lang,step:{a:s.a,b:s.b,missing:s.missing===true},phase:ui.phase(),visibleExplanation:ui.phaseText().slice(0,1000),history})});const data=await res.json().catch(()=>({}));if(generation!==epoch||key!==viewKey()||state().ended)return;if(!res.ok||typeof data.answer!=='string'||!safeArithmeticText(data.answer)||data.targetAnswer!==solution(s))throw Error(data.code||'connection');busy=false;request=null;provider=data.source==='openai'?'connected':'local';reply=data.answer;result={kind:data.scope==='clarify'?'clarify':'ai'};receive(result,reply);history.push({question,answer:reply});history=history.slice(-4);$('answer').value='';status(lang==='fr'?'Réponse IA reçue pour la question affichée. L’enseignant vérifie les explications.':'AI answer received for the displayed question. The teacher reviews the explanation.');}
 catch(error){if(generation!==epoch||key!==viewKey()||state().ended)return;busy=false;request=null;provider=error.message==='not_configured'?'not-configured':'temporarily-unavailable';unresolved=true;status(lang==='fr'?'La réponse supplémentaire n’a pas pu être obtenue. Votre question reste saisie. Réessayez, ou demandez « Explique encore » pour la méthode locale.':'The additional answer could not be retrieved. Your question is still in the input box. Retry, or ask “Explain again” for the local method.');ui.refresh();}
 finally{clearTimeout(timer);if(generation===epoch){busy=false;request=null;ui.refresh();}}}
 function render(){fresh.textContent=state().lang==='fr'?'↻ Nouvelle séance':'↻ New lesson';if(lastReply&&lastReply.key!==viewKey()){if(lastReply.result.kind!=='ai'){const reply=localReply(lastReply.result,h.current(),state().lang);if(reply)lastReply={...lastReply,key:viewKey(),reply,lang:state().lang};else lastReply=null;}else lastReply=null;}if(lastReply){$('feedback').hidden=false;$('feedback').textContent=lastReply.reply;$('caption').textContent=lastReply.reply;}if(busy){$('answer').disabled=true;document.querySelector('#answer-form button[type=submit]').disabled=true;$('mic').disabled=true;$('group-advance').disabled=true;}if(review)$('group-advance').textContent=state().lang==='fr'?'Compris · Suivant →':'Reviewed · Next →';persist();}
 fresh.onclick=()=>{if(state().started&&!state().ended&&!confirm(state().lang==='fr'?'Commencer une nouvelle séance avec d’autres problèmes ?':'Start a new lesson with different questions?'))return;ui.stop();reset();ui.refresh();status();};restore();status();
 Object.defineProperty(window,'GEM_RELIABILITY',{get:()=>({version:VERSION,sessionId:session?.id,first:session?.first,step:{id:h.current().id,a:h.current().a,b:h.current().b,missing:!!h.current().missing,answer:h.current().answer},busy,reviewRequired:review,unresolved,provider,aiRequests:requests})});
 return {render,submit,cancel,onStep,reset,ensureFresh:()=>{if(state().ended)reset();},beforeAdvance,hold:()=>busy||review||unresolved||performance.now()<holdUntil,waitingMessage:()=>state().lang==='fr'?(busy?'Réponse en cours…':review?'Lisez la correction, puis appuyez sur Suivant.':unresolved?'Question conservée · précisez votre demande.':'Temps pour lire l’explication.'):(busy?'Preparing an answer…':review?'Read the correction, then press Next.':unresolved?'Question preserved · clarify your request.':'Time to read the explanation.'),busy:()=>busy};
}
