// GEM common lesson: one content ID and progress state, two language packs.
export const LESSON_ID='gem-g2-add20-v1';
const pair=(en,fr)=>({en,fr});
export const steps=[
 {id:'welcome',min:3,a:4,b:3,title:pair('Let’s add together','Additionnons ensemble'),speech:pair('Hello, everyone! Today we will join groups and add numbers up to twenty. You can use fingers, counters, or small pieces of paper. Your classroom teacher will help us take turns.','Bonjour à tous ! Aujourd’hui, nous allons réunir des groupes et additionner jusqu’à vingt. Utilisez vos doigts, des jetons ou de petits morceaux de papier. Votre enseignant vous aidera à parler à tour de rôle.'),prompt:pair('Show four counters. Now show three more.','Montrez quatre jetons. Puis montrez trois autres jetons.'),activity:pair('Teacher: prepare up to 20 safe counters per pair. Ask students to show a group of four and a group of three.','Enseignant : préparez jusqu’à 20 jetons adaptés par binôme. Demandez de montrer un groupe de quatre et un groupe de trois.'),answer:null},
 {id:'join',min:3,a:4,b:3,title:pair('Join two groups','Réunir deux groupes'),speech:pair('There are four counters in the first group and three in the second. Adding means joining the groups to find how many there are altogether. Point to each counter once.','Il y a quatre jetons dans le premier groupe et trois dans le deuxième. Additionner, c’est réunir les groupes pour trouver combien il y en a en tout. Montrez chaque jeton une seule fois.'),prompt:pair('What is four plus three? Tell your partner, then share one answer.','Combien font quatre plus trois ? Discutez à deux, puis partagez une réponse.'),activity:pair('Let pairs join the two groups and explain how they counted. The teacher enters a representative answer.','Laissez les binômes réunir les deux groupes et expliquer leur méthode. L’enseignant saisit une réponse représentative.'),answer:7},
 {id:'count-on',min:4,a:8,b:2,title:pair('Count on','Compter à partir d’un nombre'),speech:pair('We already have eight. We do not need to start at one again. Keep eight in your head and count on two more steps. Use two fingers to keep track.','Nous avons déjà huit. Inutile de recommencer à un. Gardez huit dans votre tête et avancez de deux nombres. Utilisez deux doigts pour suivre les étapes.'),prompt:pair('What is eight plus two?','Combien font huit plus deux ?'),activity:pair('Students explain counting on. Then try 5 + 2 and 6 + 3 orally. Return to the displayed question before entering an answer.','Les élèves expliquent le comptage. Essayez ensuite 5 + 2 et 6 + 3 à l’oral. Revenez à la question affichée avant de saisir une réponse.'),answer:10},
 {id:'complete-ten',min:4,a:8,b:2,missing:true,title:pair('Make a full ten','Compléter jusqu’à dix'),speech:pair('A ten-frame has ten spaces. Eight spaces are filled. Look at the empty spaces. How many counters would fill the frame?','Un cadre de dix contient dix cases. Huit cases sont remplies. Regardez les cases vides. Combien de jetons faut-il pour compléter le cadre ?'),prompt:pair('Eight plus how many makes ten?','Huit plus combien font dix ?'),activity:pair('Draw a ten-frame with 2 rows of 5. Pairs fill 8 spaces and describe the empty spaces.','Dessinez un cadre de 2 rangées de 5 cases. Les binômes remplissent 8 cases et décrivent les cases vides.'),answer:2},
 {id:'bridge-ten',min:4,a:8,b:7,title:pair('Use ten to help','S’aider de dix'),speech:pair('We want to add eight and seven. First, move two of the seven counters to the group of eight. We now have ten and five. We have moved counters, not added extra counters.','Nous voulons additionner huit et sept. Déplaçons d’abord deux des sept jetons vers le groupe de huit. Nous avons maintenant dix et cinq. Nous avons déplacé des jetons, sans en ajouter.'),prompt:pair('What is eight plus seven? Explain your thinking.','Combien font huit plus sept ? Expliquez votre raisonnement.'),activity:pair('Pairs physically move 2 counters, then check that the total number has not changed. Use Explain again for the same instructions.','Les binômes déplacent réellement 2 jetons et vérifient que le total ne change pas. Réécoutez les mêmes consignes au besoin.'),answer:15},
 {id:'together',min:4,a:9,b:6,title:pair('Try it together','Essayons ensemble'),speech:pair('Here are nine counters and six more. Nine needs just one more to make ten. Take one counter from the six. How many are left in that second group?','Voici neuf jetons et six autres. Il manque un seul jeton à neuf pour faire dix. Prenez un jeton parmi les six. Combien en reste-t-il dans ce deuxième groupe ?'),prompt:pair('What is nine plus six?','Combien font neuf plus six ?'),activity:pair('Ask one pair to demonstrate and a second pair to explain why moving a counter preserves the total.','Un binôme montre la méthode ; un autre explique pourquoi déplacer un jeton ne change pas le total.'),answer:15},
 {id:'pair',min:5,a:7,b:5,title:pair('Work with a partner','Travailler à deux'),speech:pair('Work with a partner. Show seven counters and five more. One person moves counters to make ten. The other explains each move. Then swap roles.','Travaillez à deux. Montrez sept jetons et cinq autres. Une personne déplace les jetons pour former dix. L’autre explique chaque déplacement. Puis échangez les rôles.'),prompt:pair('What is seven plus five?','Combien font sept plus cinq ?'),activity:pair('Allow real discussion time. Extend with 6 + 5 and 8 + 4 using counters, then return to 7 + 5.','Laissez du temps pour discuter. Proposez ensuite 6 + 5 et 8 + 4 avec des jetons, puis revenez à 7 + 5.'),answer:12},
 {id:'story',min:4,a:6,b:8,title:pair('A classroom story','Une histoire de classe'),speech:pair('Six children are at a table. Eight more children join them. We want to know how many children there are altogether. We are joining two groups, so we add.','Six enfants sont autour d’une table. Huit autres enfants les rejoignent. Nous cherchons combien il y a d’enfants en tout. Nous réunissons deux groupes : il faut donc additionner.'),prompt:pair('How many children are there altogether?','Combien y a-t-il d’enfants en tout ?'),activity:pair('Retell the story with counters, not with student names. Ask why addition fits this story.','Racontez l’histoire avec des jetons, sans utiliser de noms d’élèves. Demandez pourquoi on utilise l’addition.'),answer:14},
 {id:'practice',min:4,a:9,b:8,title:pair('Choose your method','Choisir sa méthode'),speech:pair('Look at nine plus eight. You may count on or make ten. Choose a method and explain it to a partner. Listen to a different method too.','Regardez neuf plus huit. Vous pouvez compter à partir de neuf ou compléter jusqu’à dix. Choisissez une méthode et expliquez-la à un camarade. Écoutez aussi une autre méthode.'),prompt:pair('What is nine plus eight?','Combien font neuf plus huit ?'),activity:pair('Invite two different methods. No marks or ranking: focus on a clear explanation.','Invitez deux méthodes différentes. Pas de note ni de classement : privilégiez une explication claire.'),answer:17},
 {id:'swap',min:2,a:5,b:8,title:pair('Swap the groups','Échanger les groupes'),speech:pair('Show five counters and eight counters. Now swap the places of the groups. Did you add or remove any counters? The total stays the same.','Montrez cinq jetons et huit jetons. Échangez maintenant la place des groupes. Avez-vous ajouté ou retiré des jetons ? Le total reste le même.'),prompt:pair('What is five plus eight? Is eight plus five the same total?','Combien font cinq plus huit ? Huit plus cinq donnent-ils le même total ?'),activity:pair('Ask students to justify their answer using the groups, rather than guessing a rule.','Demandez une justification avec les groupes plutôt qu’une règle devinée.'),answer:13},
 {id:'check',min:2,a:7,b:6,title:pair('Explain what you learned','Expliquer ce qu’on a appris'),speech:pair('Here is seven plus six. Show how you can make ten first. Tell your teacher what you moved and what stayed the same.','Voici sept plus six. Montrez comment former dix d’abord. Expliquez à votre enseignant ce que vous avez déplacé et ce qui n’a pas changé.'),prompt:pair('What is seven plus six?','Combien font sept plus six ?'),activity:pair('Listen to explanations to decide whether the next lesson should review or extend this skill.','Écoutez les explications pour décider si la prochaine séance doit revoir ou approfondir cette compétence.'),answer:13},
 {id:'summary',min:1,a:8,b:7,title:pair('We can add together','Nous savons additionner'),speech:pair('Today we joined groups, counted on, and made ten. Moving counters between groups does not change the total. Thank you for explaining and listening. Your teacher will help you choose the next lesson.','Aujourd’hui, nous avons réuni des groupes, compté à partir d’un nombre et complété jusqu’à dix. Déplacer les jetons entre les groupes ne change pas le total. Merci d’avoir expliqué et écouté. Votre enseignant vous aidera à choisir la prochaine leçon.'),prompt:pair('Tell a partner one method you can use.','Présentez à un camarade une méthode que vous savez utiliser.'),activity:pair('End when the class is ready. This is one pilot lesson, not a full Grade 2 curriculum.','Terminez lorsque la classe est prête. Il s’agit d’une séance pilote, et non de tout le programme du niveau 2.'),answer:null}
];
export const duration=(index,minutes)=>Math.round(steps[index].min*60*minutes/40);
export const norm=s=>String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').normalize('NFC').replace(/[’']/g,' ').replace(/-/g,' ').replace(/\s+/g,' ').trim();
const en=['zero','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen','twenty'];
const fr=['zero','un','deux','trois','quatre','cinq','six','sept','huit','neuf','dix','onze','douze','treize','quatorze','quinze','seize','dix sept','dix huit','dix neuf','vingt'];
const ko=['영','일','이','삼','사','오','육','칠','팔','구','십','십일','십이','십삼','십사','십오','십육','십칠','십팔','십구','이십'];
export function numberAnswer(input){
 let s=norm(input).replace(/[.!?。]+$/g,'').replace(/^(?:the answer is|my answer is|it is|it s|answer|la reponse est|c est|reponse|답은|정답은)\s*/,'').replace(/\s*(?:입니다|이에요|예요|개)$/,'').trim();
 if(/^\d{1,2}$/.test(s))return Number(s);
 for(const list of [en,fr,ko]){const i=list.indexOf(s);if(i>=0)return i;}
 return null;
}
export function explain(a,b,lang){
 const sum=a+b;
 if(a>0&&a<10&&sum>=10){const need=10-a,rest=b-need;return lang==='fr'?`${a} a besoin de ${need} pour faire dix. Séparons ${b} en ${need} et ${rest}. ${a} plus ${need} font dix. Dix plus ${rest} font ${sum}.`:`${a} needs ${need} to make ten. Split ${b} into ${need} and ${rest}. ${a} plus ${need} is ten. Ten plus ${rest} is ${sum}.`;}
 return lang==='fr'?`Réunissons ${a} et ${b}. ${a} plus ${b} font ${sum}. On peut compter ${b} de plus à partir de ${a}.`:`Join ${a} and ${b}. ${a} plus ${b} is ${sum}. Start with ${a} and count on ${b} more.`;
}
export function interpret(input,step){
 const s=norm(input);const n=numberAnswer(input);
 if(n!==null&&step.answer!==null)return {kind:n===step.answer?'correct':'retry',n};
 if(/(?:why.*(?:ten|10)|pourquoi.*(?:dix|10)|왜.*10|make ten|faire dix|완성)/.test(s))return{kind:'ten'};
 if(/(?:what.*addition|what.*adding|qu.est.ce.*addition|additionner.*dire|덧셈.*뭐)/.test(s))return{kind:'meaning'};
 if(/^(?:again|repeat|explain|explain again|reexpliquer|explique|encore|다시|쉽게|모르겠습니다)/.test(s)||/don.t know|ne sais pas|모르/.test(s))return{kind:'explain'};
 if(/another example|autre exemple|다른 예/.test(s))return{kind:'example'};
 let expr=s.replace(/^(?:what is|what s|calculate|combien font|combien fait|calcule)\s*/,'').replace(/[?!.,]$/,'').trim();
 for(let i=20;i>=0;i--){for(const word of [en[i],fr[i]])expr=expr.replace(new RegExp('\\b'+word+'\\b','g'),String(i));}
 expr=expr.replace(/\b(?:plus|et)\b/g,'+').replace(/더하기/g,'+');
 const m=expr.match(/^(\d{1,2})\s*\+\s*(\d{1,2})(?:\s*=\s*(\d{1,2}))?$/);
 if(m){const a=Number(m[1]),b=Number(m[2]),c=m[3]===undefined?null:Number(m[3]);if(a+b<=20){if(c!==null&&a===step.a&&b===step.b&&!step.missing)return{kind:c===a+b?'correct':'retry',n:c};return{kind:'calculation',a,b,claim:c};}}
 return{kind:'scope'};
}
export function response(result,step,lang){
 const f=lang==='fr';const detail=step.missing?(f?`${step.a} plus ${step.answer} font dix.`:`${step.a} plus ${step.answer} is ten.`):explain(step.a,step.b,lang);
 switch(result.kind){
 case 'correct':return (f?'Oui. Merci pour votre réponse. ':'Yes. Thank you for sharing. ')+detail;
 case 'retry':return f?`Reprenons ensemble. Regardez les groupes et comptez soigneusement. ${step.missing?'Combien de cases sont vides ?':'Vous pouvez déplacer des jetons pour former dix, sans en ajouter.'} Essayez de nouveau.`:`Let’s work through it together. Look at the groups and count carefully. ${step.missing?'How many spaces are empty?':'You can move counters to make ten without adding extra counters.'} Try again.`;
 case 'meaning':return f?'Additionner, c’est réunir des quantités pour trouver le total. Par exemple, deux jetons et un jeton font trois jetons.':'Adding means joining amounts to find the total. For example, two counters and one counter make three counters.';
 case 'ten':return f?'Dix est un groupe facile à reconnaître. On déplace des jetons pour compléter ce groupe, sans changer le total. '+explain(8,7,lang):'Ten is an easy group to recognize. We move counters to complete it without changing the total. '+explain(8,7,lang);
 case 'example':return explain(6,7,lang);
 case 'calculation':return (result.claim!==null&&result.claim!==result.a+result.b?(f?'Vérifions ce calcul. ':'Let’s check that calculation. '):'')+explain(result.a,result.b,lang);
 case 'explain':return detail;
 default:return f?'Ce pilote répond aux additions jusqu’à vingt et aux questions préparées sur cette leçon. Essayez « 6 + 7 », « Pourquoi faire dix ? » ou « Explique encore ». Les questions libres à une IA ne sont pas encore connectées.':'This pilot answers additions up to twenty and prepared questions about this lesson. Try “6 + 7”, “Why make ten?” or “Explain again”. Open-ended AI questions are not connected yet.';
 }
}
