let micPermissionTimer=0,micStopTimer=0,micChecking=false,micTestStream=null,micTestContext=null,micTestTimer=0,micTestToken=0,micDiagnostic='';
function micStatus(message){micDiagnostic=message;$('mic-status').textContent=message;}
function micError(code){const messages={
 'not-allowed':['Microphone permission blocked. Use the address-bar site controls to allow Microphone; also check Windows microphone privacy settings.','Autorisation du micro bloquée. Autorisez le micro dans les réglages du site et vérifiez la confidentialité du micro dans Windows.','마이크 권한 차단: 주소창 왼쪽 사이트 설정과 Windows 마이크 권한을 확인해 주세요.'],
 'audio-capture':['No usable microphone. Check the input device, mute switch and other apps.','Aucun micro utilisable. Vérifiez l’entrée audio, la sourdine et les autres applications.','입력 장치·음소거·다른 앱의 마이크 사용을 확인해 주세요.'],
 'network':['The browser speech recognition service could not connect. Microphone hardware may still be working. Try the mic check; type while offline.','Le service de reconnaissance vocale ne se connecte pas. Le micro peut fonctionner. Vérifiez-le ; saisissez du texte hors ligne.','음성인식 서비스 연결 오류입니다. 아래 마이크 신호 검사를 눌러 장치 문제와 구분해 주세요.'],
 'no-speech':['No speech detected. Speak after the Listening message, closer to the microphone.','Aucune parole détectée. Parlez après le message d’écoute, plus près du micro.','듣는 중 표시가 나온 후 마이크 가까이에서 말씀해 주세요.'],
 'service-not-allowed':['This browser does not allow this recognition service. Try Chrome or use typed answers.','Ce navigateur n’autorise pas ce service. Essayez Chrome ou saisissez la réponse.','이 브라우저에서 음성인식 서비스를 허용하지 않습니다. Chrome 또는 문자 입력을 사용해 주세요.'],
 'language-not-supported':['Speech recognition does not support the selected language on this browser. Use typed answers.','La reconnaissance de ce navigateur ne prend pas en charge cette langue. Saisissez la réponse.','이 브라우저의 선택 언어 음성인식 미지원입니다. 문자 입력은 계속 가능합니다.'],
 'unsupported':['Speech recognition is unavailable in this browser. Use Chrome or type.','La reconnaissance est indisponible dans ce navigateur. Utilisez Chrome ou saisissez du texte.','브라우저 음성인식 미지원입니다. Chrome 또는 문자 입력을 사용해 주세요.'],
 'insecure':['Microphone access requires HTTPS. Open the original classroom link.','Le micro nécessite HTTPS. Ouvrez le lien original de la classe.','HTTPS 원본 시험 교실 주소로 열어 주세요.'],
 'permission-timeout':['Waiting for permission ended. Press Speak again and respond to the browser permission prompt.','Attente d’autorisation terminée. Appuyez sur Parler et répondez à la demande du navigateur.','권한 확인 대기가 끝났습니다. 다시 말하기를 누르고 브라우저 요청에 응답해 주세요.'],
 'aborted':['Microphone stopped.','Micro arrêté.','마이크가 중지되었습니다.']};
 const a=messages[code]||['Microphone error. Try the microphone check.','Erreur du micro. Lancez la vérification.','마이크 검사를 눌러 확인해 주세요.'];micStatus(`${a[state.lang==='fr'?1:0]} [${code}] · ${a[2]}`);}
function stopMic(){clearTimeout(micTimer);clearTimeout(micPermissionTimer);clearTimeout(micStopTimer);if(rec){const r=rec;rec=null;r.onstart=r.onresult=r.onend=r.onerror=r.onaudiostart=null;try{r.abort();}catch{}}$('mic').textContent=text('mic');}
function requestMicStop(){if(!rec)return;const r=rec;micStatus(state.lang==='fr'?'Finalisation du texte…':'Finishing recognition…');try{r.stop();}catch(error){stopMic();micError(error.name||'aborted');}micStopTimer=setTimeout(()=>{if(rec===r){stopMic();micError('no-speech');}},5000);}
function startMic(){if(rec){requestMicStop();return;}if(!globalThis.isSecureContext){micError('insecure');return;}const R=globalThis.SpeechRecognition||globalThis.webkitSpeechRecognition;if(!R){micError('unsupported');return;}stopSpeech();stopMic();const r=new R();rec=r;let finalText='',interim='',received=false,endedWithError=false;
 r.lang=state.lang==='fr'?'fr-FR':'en-US';r.continuous=false;r.interimResults=true;r.maxAlternatives=1;
 const onReady=()=>{if(rec!==r)return;clearTimeout(micPermissionTimer);$('mic').textContent=state.lang==='fr'?'■ Terminer':'■ Finish';micStatus(text('micListen')+' · '+r.lang);clearTimeout(micTimer);micTimer=setTimeout(()=>{if(rec===r)requestMicStop();},15000);};r.onstart=onReady;r.onaudiostart=onReady;
 r.onresult=e=>{if(rec!==r)return;finalText='';interim='';for(let i=0;i<e.results.length;i++){const item=e.results[i],value=item[0]?.transcript||'';if(item.isFinal)finalText+=' '+value;else interim+=' '+value;}const value=(finalText||interim).trim().slice(0,240);if(value){received=true;$('answer').value=value;micStatus(text('micReview'));}};
 r.onend=()=>{if(rec!==r)return;rec=null;clearTimeout(micTimer);clearTimeout(micStopTimer);clearTimeout(micPermissionTimer);$('mic').textContent=text('mic');if(received){micStatus(text('micReview'));}else if(!endedWithError)micError('no-speech');};
 r.onerror=e=>{if(rec!==r)return;endedWithError=true;const code=e.error||'recognition-error';stopMic();micError(code);};
 try{r.start();micStatus(state.lang==='fr'?'Autorisez le micro si le navigateur le demande…':'Allow the microphone if the browser asks…');micPermissionTimer=setTimeout(()=>{if(rec===r){stopMic();micError('permission-timeout');}},60000);}catch(error){stopMic();micError(error.name==='NotAllowedError'?'not-allowed':error.name||'recognition-error');}}
function stopMicCheck(){micTestToken++;clearTimeout(micTestTimer);micTestStream?.getTracks().forEach(t=>t.stop());micTestStream=null;if(micTestContext){micTestContext.close().catch(()=>{});micTestContext=null;}micChecking=false;$('mic-level').hidden=true;$('mic-check').disabled=false;}
async function checkMicrophone(){if(micChecking){stopMicCheck();return;}stopMic();stopSpeech();micChecking=true;const token=++micTestToken;$('mic-check').disabled=true;micStatus(state.lang==='fr'?'Test local de 5 secondes. Aucune sauvegarde ni transmission par GEM. Autorisez le micro.':'5-second local input test. GEM does not save or send audio. Allow the microphone.');
 try{if(!globalThis.isSecureContext)throw {name:'SecurityError'};if(!navigator.mediaDevices?.getUserMedia)throw {name:'NotSupportedError'};const stream=await navigator.mediaDevices.getUserMedia({audio:true,video:false});if(token!==micTestToken){stream.getTracks().forEach(t=>t.stop());return;}micTestStream=stream;const C=globalThis.AudioContext||globalThis.webkitAudioContext;if(!C)throw {name:'NotSupportedError'};const ctx=new C();micTestContext=ctx;await ctx.resume();if(token!==micTestToken)return;const analyser=ctx.createAnalyser();analyser.fftSize=512;ctx.createMediaStreamSource(stream).connect(analyser);const data=new Uint8Array(512);let peak=0,started=performance.now();$('mic-level').hidden=false;
 const tick=()=>{if(token!==micTestToken)return;analyser.getByteTimeDomainData(data);let sq=0;for(const b of data)sq+=((b-128)/128)**2;const rms=Math.sqrt(sq/data.length);peak=Math.max(peak,rms);$('mic-level').value=Math.min(1,rms*8);micStatus((state.lang==='fr'?'Parlez maintenant : signal local ':'Speak now: local input signal ')+Math.round(rms*100)+'% · 마이크에 말씀해 주세요.');if(performance.now()-started<5000){micTestTimer=setTimeout(tick,90);return;}const result=peak>.008?['Microphone signal detected. If speech-to-text fails, check recognition permission/network.','Signal du micro détecté. Si le texte ne s’affiche pas, vérifiez le service de reconnaissance.','마이크 신호 정상. 문자 변환 실패는 음성인식 서비스·언어·연결을 확인해야 합니다.']:['Microphone opened but no clear signal detected. Check mute and selected input device.','Micro ouvert, mais aucun signal net. Vérifiez la sourdine et l’entrée audio.','마이크는 열렸지만 신호가 약합니다. 음소거와 입력 장치를 확인해 주세요.'];stopMicCheck();micStatus(result[state.lang==='fr'?1:0]+' · '+result[2]);};tick();
 }catch(error){if(token!==micTestToken)return;stopMicCheck();const code={NotAllowedError:'not-allowed',SecurityError:'not-allowed',NotFoundError:'audio-capture',NotReadableError:'audio-capture',NotSupportedError:'unsupported'}[error.name]||error.name||'audio-capture';micError(code);}}
