import assert from 'node:assert/strict';
import {makeSession,validateSession,activateSession,packageFor} from './reliable-lessons.mjs';
import {classify,localReply,validStep,solution,explainStep,safeArithmeticText} from './tutor-core.mjs';
let seed=20260924;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/2**32;};let recent=[];
for(let i=0;i<120;i++){const session=makeSession(recent,random);assert.ok(validateSession(session));assert.ok(!recent.slice(-12).includes(session.first));recent.push(session.first);activateSession(session.steps);const qs=session.steps.filter(s=>s.answer!==null);assert.equal(qs.length,10);assert.equal(new Set(qs.map(s=>`${s.missing?'?':'+'}:${s.a}:${s.b}`)).size,10);for(const s of qs){assert.ok(validStep(s));assert.equal(s.answer,solution(s));for(const lang of ['en','fr']){for(const kind of ['explain','count-on','ten','empty','example','conservation'])assert.ok(safeArithmeticText(localReply({kind},s,lang)));assert.ok(safeArithmeticText(localReply({kind:'incorrect',n:solution(s)+1},s,lang)));assert.ok(packageFor(s.id).summary[lang].includes(String(solution(s))));}}}
const s={id:'together',a:9,b:6,answer:15,missing:false};for(const q of ['15','fifteen','quinze','The answer is 15.','C’est quinze.','답은 15입니다'])assert.equal(classify(q,s).kind,'correct',q);for(const q of ['14','fourteen','quatorze','9+6=14'])assert.equal(classify(q,s).kind,'incorrect',q);for(const q of ['Why is 9 + 6 not 14?','Pourquoi 9 + 6 ne fait pas 14 ?','15 or 16','not fifteen'])assert.notEqual(classify(q,s).kind,'correct',q);assert.equal(classify('What is six plus seven?',s).kind,'calculation');assert.equal(classify('Combien font six plus sept ?',s).kind,'calculation');assert.equal(classify('Why count from nine?',s).kind,'count-on');for(const lang of ['en','fr']){const r=localReply(classify('Why count from nine?',s),s,lang);assert.ok(r.includes('9'));assert.ok(r.includes('15'));assert.ok(!r.includes('8 + 2'));assert.ok(safeArithmeticText(explainStep({a:8,b:2,missing:true},lang)));}assert.equal(safeArithmeticText('9 + 6 = 16.'),false);assert.equal(safeArithmeticText('9 + 6 = 15.'),true);
console.log('RELIABILITY UNIT PASS: 120 new sessions / 1200 exact questions; EN/FR arithmetic, no recent repeated start, context and ambiguity checks.');
const {answerQuestion}=await import('../api/mission-chat.js');const old=process.env.OPENAI_API_KEY;process.env.OPENAI_API_KEY='test-placeholder-not-a-secret';
try{let calls=0;const mock=async()=>{calls++;return {ok:true,json:async()=>({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({answer:'9 + 6 = 15. Use ten and five.',scope:'math',targetAnswer:15})}]}]})};};const r=await answerQuestion({question:'Can I regroup the counters?',lang:'en',step:s},{fetchImpl:mock});assert.equal(r.status,200);assert.equal(calls,1);const bad=await answerQuestion({question:'Test validation of a different question',lang:'en',step:s},{fetchImpl:async()=>({ok:true,json:async()=>({output:[{content:[{type:'output_text',text:JSON.stringify({answer:'9 + 6 = 16.',scope:'math',targetAnswer:15})}]}]})})});assert.equal(bad.code,'reply_validation');}finally{if(old===undefined)delete process.env.OPENAI_API_KEY;else process.env.OPENAI_API_KEY=old;}
