// GEM common learning progression, not a claim of national curriculum alignment.
export const LANGS=['en','fr','ne','ur','sw'];
const titles=(s)=>Object.fromEntries(s.split('|').map((v,i)=>[LANGS[i],v]));
const rows={
math:[
 ['Counting to 20|Compter jusqu’à 20|२० सम्म गन्ती|۲۰ تک گنتی|Kuhesabu hadi 20','Adding and taking away|Ajouter et retirer|जोड्ने र घटाउने|جمع اور تفریق|Kuongeza na kupunguza','Shapes and patterns|Formes et suites|आकार र ढाँचा|شکلیں اور نمونے|Maumbo na ruwaza','Length and time|Longueur et temps|लम्बाइ र समय|لمبائی اور وقت|Urefu na muda'],
 ['Addition within 20|Addition jusqu’à 20|२० भित्र जोड|۲۰ تک جمع|Kujumlisha hadi 20','Place value to 100|Numération jusqu’à 100|१०० सम्म स्थानमान|۱۰۰ تک مقامی قیمت|Thamani ya nafasi hadi 100','Equal groups|Groupes égaux|बराबर समूह|برابر گروہ|Makundi sawa','Measurement and data|Mesures et données|मापन र तथ्याङ्क|پیمائش اور اعداد و شمار|Vipimo na data'],
 ['Multiplication and division|Multiplication et division|गुणन र भाग|ضرب اور تقسیم|Kuzidisha na kugawanya','Fractions of a whole|Fractions d’un tout|पूर्ण वस्तुको भिन्न|کُل کے کسر|Sehemu za kitu kizima','Perimeter and area|Périmètre et aire|परिमिति र क्षेत्रफल|محیط اور رقبہ|Mzingo na eneo','Time and tables|Heure et tableaux|समय र तालिका|وقت اور جدول|Muda na majedwali'],
 ['Multi-digit arithmetic|Calcul à plusieurs chiffres|बहुअङ्कीय गणना|کثیر ہندسی حساب|Hesabu za tarakimu nyingi','Equivalent fractions|Fractions équivalentes|बराबर भिन्न|مساوی کسر|Sehemu zilizo sawa','Angles and symmetry|Angles et symétrie|कोण र सममिति|زاویے اور تقارن|Pembe na ulinganifu','Decimals and measurement|Décimaux et mesures|दशमलव र मापन|اعشاریے اور پیمائش|Desimali na vipimo'],
 ['Fraction operations|Calcul avec les fractions|भिन्नका गणना|کسروں کے حساب|Hesabu za sehemu','Decimal operations|Calcul avec les décimaux|दशमलवका गणना|اعشاری حساب|Hesabu za desimali','Volume and coordinates|Volume et coordonnées|आयतन र निर्देशाङ्क|حجم اور محددات|Ujazo na viwianishi','Patterns and data|Suites et données|ढाँचा र तथ्याङ्क|نمونے اور اعداد و شمار|Ruwaza na data'],
 ['Ratios and percentages|Rapports et pourcentages|अनुपात र प्रतिशत|نسبت اور فیصد|Uwiano na asilimia','Integers and expressions|Entiers et expressions|पूर्णाङ्क र व्यञ्जक|صحیح اعداد اور الجبری عبارتیں|Namba kamili na semi','Area and volume|Aire et volume|क्षेत्रफल र आयतन|رقبہ اور حجم|Eneo na ujazo','Statistical questions|Questions statistiques|तथ्याङ्कीय प्रश्न|شماریاتی سوالات|Maswali ya takwimu'],
 ['Proportional relationships|Proportionnalité|समानुपातिक सम्बन्ध|متناسب تعلقات|Mahusiano ya uwiano','Rational numbers and equations|Nombres rationnels et équations|परिमेय सङ्ख्या र समीकरण|ناطق اعداد اور مساوات|Namba za uwiano na milinganyo','Geometry and scale|Géométrie et échelle|ज्यामिति र मापन अनुपात|ہندسہ اور پیمانہ|Jiometri na skeli','Probability and samples|Probabilités et échantillons|सम्भावना र नमुना|احتمال اور نمونے|Uwezekano na sampuli'],
 ['Linear equations|Équations linéaires|रेखीय समीकरण|خطی مساوات|Milinganyo ya mstari','Functions and graphs|Fonctions et graphiques|फलन र रेखाचित्र|تفاعل اور گراف|Vigezo tegemezi na grafu','Right triangles|Triangles rectangles|समकोण त्रिभुज|قائم الزاویہ مثلث|Pembetatu za pembe mraba','Exponents and scientific notation|Puissances et notation scientifique|घात र वैज्ञानिक सङ्केत|قوتیں اور سائنسی علامت|Vipeo na uandishi wa kisayansi'],
 ['Algebraic reasoning|Raisonnement algébrique|बीजगणितीय तर्क|الجبری استدلال|Hoja za aljebra','Quadratic expressions|Expressions du second degré|द्विघात व्यञ्जक|درجہ دوم کی عبارتیں|Semi za daraja la pili','Congruence and similarity|Isométrie et similitude|सर्वाङ्गसमता र समानरूपता|تطابق اور تشابہ|Mlingano na ufanano','Two-variable data|Données à deux variables|दुई चलको तथ्याङ्क|دو متغیرات کے اعداد و شمار|Data za vigeu viwili'],
 ['Quadratic equations|Équations du second degré|द्विघात समीकरण|درجہ دوم کی مساوات|Milinganyo ya daraja la pili','Trigonometry|Trigonométrie|त्रिकोणमिति|مثلثیات|Trigonometria','Circles and proofs|Cercles et démonstrations|वृत्त र प्रमाण|دائرے اور ثبوت|Duara na uthibitisho','Probability models|Modèles probabilistes|सम्भावनाका नमुना|احتمالی نمونے|Miundo ya uwezekano'],
 ['Exponential functions|Fonctions exponentielles|घाताङ्कीय फलन|اساسی تفاعل|Vigezo tegemezi vya kipeo','Sequences and series|Suites et séries|अनुक्रम र श्रेणी|تسلسل اور سلسلے|Mifuatano na mifululizo','Trigonometric functions|Fonctions trigonométriques|त्रिकोणमितीय फलन|مثلثی تفاعل|Vigezo tegemezi vya trigonometria','Statistical inference|Inférence statistique|तथ्याङ्कीय अनुमान|شماریاتی استنباط|Hitimisho la kitakwimu'],
 ['Rates of change|Taux de variation|परिवर्तनको दर|تبدیلی کی شرح|Viwango vya mabadiliko','Accumulation and area|Accumulation et aire|सञ्चय र क्षेत्रफल|تراکم اور رقبہ|Mkusanyiko na eneo','Functions and modelling|Fonctions et modélisation|फलन र नमुना निर्माण|تفاعل اور نمونہ سازی|Vigezo tegemezi na uundaji wa mifano','Interpreting statistical evidence|Interpréter les résultats statistiques|तथ्याङ्कीय प्रमाणको व्याख्या|شماریاتی شواہد کی تشریح|Kutafsiri ushahidi wa takwimu']
],
science:[
 ['Observing plants|Observer les plantes|बिरुवा अवलोकन|پودوں کا مشاہدہ|Kuchunguza mimea','Our senses|Nos sens|हाम्रा इन्द्रिय|ہمارے حواس|Hisi zetu','Everyday materials|Matériaux du quotidien|दैनिक सामग्री|روزمرہ مواد|Vifaa vya kila siku','Day and night|Le jour et la nuit|दिन र रात|دن اور رات|Mchana na usiku'],
 ['What plants need|Besoins des plantes|बिरुवालाई चाहिने कुरा|پودوں کی ضروریات|Mahitaji ya mimea','Solids and liquids|Solides et liquides|ठोस र तरल|ٹھوس اور مائع|Vitu vigumu na vimiminika','Pushes and pulls|Pousser et tirer|धकेल्ने र तान्ने|دھکیلنا اور کھینچنا|Kusukuma na kuvuta','Weather observations|Observer la météo|मौसम अवलोकन|موسم کا مشاہدہ|Kuchunguza hali ya hewa'],
 ['Habitats and food chains|Habitats et chaînes alimentaires|वासस्थान र खाद्य शृङ्खला|مسکن اور غذائی زنجیریں|Makazi na minyororo ya chakula','Magnets|Les aimants|चुम्बक|مقناطیس|Sumaku','Light and shadows|Lumière et ombres|प्रकाश र छायाँ|روشنی اور سائے|Mwanga na vivuli','Water and soil|Eau et sol|पानी र माटो|پانی اور مٹی|Maji na udongo'],
 ['Body systems|Systèmes du corps|शरीरका प्रणाली|جسم کے نظام|Mifumo ya mwili','States of matter|États de la matière|पदार्थका अवस्था|مادے کی حالتیں|Hali za maada','Sound and vibrations|Son et vibrations|ध्वनि र कम्पन|آواز اور ارتعاش|Sauti na mitetemo','The water cycle|Le cycle de l’eau|जलचक्र|آبی چکر|Mzunguko wa maji'],
 ['Plant reproduction|Reproduction des plantes|बिरुवाको प्रजनन|پودوں کی افزائش|Uzazi wa mimea','Mixtures and separation|Mélanges et séparation|मिश्रण र पृथकीकरण|آمیزے اور علیحدگی|Michanganyiko na utenganishaji','Simple circuits|Circuits simples|सरल परिपथ|سادہ برقی سرکٹ|Saketi rahisi','Earth and space observations|Observer la Terre et l’espace|पृथ्वी र अन्तरिक्ष अवलोकन|زمین اور خلا کا مشاہدہ|Uchunguzi wa Dunia na anga'],
 ['Cells and microscopes|Cellules et microscopes|कोशिका र सूक्ष्मदर्शक|خلیے اور خوردبین|Seli na hadubini','Particles and materials|Particules et matériaux|कण र पदार्थ|ذرات اور مواد|Chembe na maada','Forces and motion|Forces et mouvement|बल र गति|قوتیں اور حرکت|Nguvu na mwendo','Rocks and resources|Roches et ressources|चट्टान र स्रोत|چٹانیں اور وسائل|Miamba na rasilimali'],
 ['Nutrition and digestion|Nutrition et digestion|पोषण र पाचन|غذائیت اور ہاضمہ|Lishe na mmeng’enyo','Atoms and elements|Atomes et éléments|परमाणु र तत्त्व|ایٹم اور عناصر|Atomi na elementi','Energy transfers|Transferts d’énergie|ऊर्जा स्थानान्तरण|توانائی کی منتقلی|Uhamishaji wa nishati','Ecosystem interactions|Interactions des écosystèmes|पारिस्थितिक अन्तरक्रिया|ماحولیاتی باہمی تعلقات|Mahusiano katika mifumo ikolojia'],
 ['Respiration and circulation|Respiration et circulation|श्वसन र रक्तसञ्चार|تنفس اور دوران خون|Upumuaji na mzunguko wa damu','Chemical reactions|Réactions chimiques|रासायनिक प्रतिक्रिया|کیمیائی تعاملات|Mmenyuko wa kemikali','Waves and light|Ondes et lumière|तरङ्ग र प्रकाश|لہریں اور روشنی|Mawimbi na mwanga','Weather and climate data|Données météo et climat|मौसम र जलवायु तथ्याङ्क|موسمی اور آب و ہوا کے اعداد و شمار|Data za hali ya hewa na tabianchi'],
 ['Cells and inheritance|Cellules et hérédité|कोशिका र वंशाणुगति|خلیے اور وراثت|Seli na urithi','Chemical bonds|Liaisons chimiques|रासायनिक बन्ध|کیمیائی بند|Vifungo vya kemikali','Electricity and magnetism|Électricité et magnétisme|विद्युत् र चुम्बकत्व|بجلی اور مقناطیسیت|Umeme na usumaku','Water quality investigations|Étudier la qualité de l’eau|पानीको गुणस्तर अध्ययन|پانی کے معیار کی تحقیق|Uchunguzi wa ubora wa maji'],
 ['Human physiology|Physiologie humaine|मानव शरीरक्रिया|انسانی فعلیات|Fiziolojia ya binadamu','Quantities in chemistry|Quantités en chimie|रसायनमा मात्रा|کیمیا میں مقداریں|Kiasi katika kemia','Motion and forces|Mouvement et forces|गति र बल|حرکت اور قوتیں|Mwendo na nguvu','Energy resources|Ressources énergétiques|ऊर्जाका स्रोत|توانائی کے وسائل|Rasilimali za nishati'],
 ['Enzymes and metabolism|Enzymes et métabolisme|इन्जाइम र चयापचय|خامرے اور تحول|Enzimu na metaboli','Acids and reaction rates|Acides et vitesse de réaction|अम्ल र प्रतिक्रिया दर|تیزاب اور تعامل کی رفتار|Asidi na kasi ya mmenyuko','Waves and circuits|Ondes et circuits|तरङ्ग र परिपथ|لہریں اور سرکٹ|Mawimbi na saketi','Environmental measurements|Mesures environnementales|वातावरणीय मापन|ماحولیاتی پیمائش|Vipimo vya mazingira'],
 ['Genetics and cell regulation|Génétique et régulation cellulaire|आनुवंशिकी र कोशिका नियमन|جینیات اور خلیاتی نظم|Jenetiki na udhibiti wa seli','Equilibrium and organic chemistry|Équilibre et chimie organique|सन्तुलन र जैविक रसायन|توازن اور نامیاتی کیمیا|Msawazo na kemia ya kikaboni','Fields and electromagnetism|Champs et électromagnétisme|क्षेत्र र विद्युत् चुम्बकत्व|میدان اور برقی مقناطیسیت|Nyuga na sumakuumeme','Evaluating scientific evidence|Évaluer les preuves scientifiques|वैज्ञानिक प्रमाण मूल्याङ्कन|سائنسی شواہد کا جائزہ|Kutathmini ushahidi wa kisayansi']
],
english:[
 ['Greetings and names|Salutations et noms|अभिवादन र नाम|سلام اور نام|Salamu na majina','Sounds and letters|Sons et lettres|ध्वनि र अक्षर|آوازیں اور حروف|Sauti na herufi','Colours and numbers|Couleurs et nombres|रङ र सङ्ख्या|رنگ اور اعداد|Rangi na namba','Classroom words|Mots de la classe|कक्षाका शब्द|جماعت کے الفاظ|Maneno ya darasani'],
 ['Everyday sentences|Phrases du quotidien|दैनिक वाक्य|روزمرہ جملے|Sentensi za kila siku','Reading short words|Lire des mots courts|छोटा शब्द पढ्ने|چھوٹے الفاظ پڑھنا|Kusoma maneno mafupi','People and places|Personnes et lieux|मानिस र स्थान|لوگ اور جگہیں|Watu na maeneo','Simple questions|Questions simples|सरल प्रश्न|سادہ سوالات|Maswali rahisi'],
 ['Describing things|Décrire les objets|वस्तुको वर्णन|چیزوں کی وضاحت|Kueleza vitu','Reading short stories|Lire des histoires courtes|छोटा कथा पढ्ने|مختصر کہانیاں پڑھنا|Kusoma hadithi fupi','Daily routines|Habitudes quotidiennes|दैनिक काम|روزمرہ معمولات|Shughuli za kila siku','Writing sentences|Écrire des phrases|वाक्य लेख्ने|جملے لکھنا|Kuandika sentensi'],
 ['Past and present|Passé et présent|भूत र वर्तमान|ماضی اور حال|Wakati uliopita na uliopo','Reading for meaning|Lire pour comprendre|अर्थ बुझेर पढ्ने|مطلب سمجھ کر پڑھنا|Kusoma kwa kuelewa','Giving directions|Donner des indications|दिशा बताउने|راستہ بتانا|Kuelekeza njia','Writing paragraphs|Écrire des paragraphes|अनुच्छेद लेख्ने|پیراگراف لکھنا|Kuandika aya'],
 ['Plans and possibilities|Projets et possibilités|योजना र सम्भावना|منصوبے اور امکانات|Mipango na uwezekano','Stories and viewpoints|Récits et points de vue|कथा र दृष्टिकोण|کہانیاں اور نقطۂ نظر|Hadithi na mitazamo','Comparing information|Comparer des informations|सूचना तुलना|معلومات کا موازنہ|Kulinganisha taarifa','Writing descriptions|Écrire des descriptions|वर्णन लेख्ने|توصیفی تحریر|Kuandika maelezo'],
 ['Conversation strategies|Stratégies de conversation|संवादका तरिका|گفتگو کی حکمت عملی|Mbinu za mazungumzo','Reading nonfiction|Lire des textes documentaires|तथ्यपरक लेख पढ्ने|معلوماتی متن پڑھنا|Kusoma maandishi ya taarifa','Tenses in context|Les temps en contexte|सन्दर्भमा काल|سیاق میں زمانے|Nyakati katika muktadha','Paragraph organisation|Organiser un paragraphe|अनुच्छेदको संरचना|پیراگراف کی ترتیب|Mpangilio wa aya'],
 ['Expressing opinions|Exprimer une opinion|राय व्यक्त गर्ने|رائے کا اظہار|Kueleza maoni','Reading evidence|Repérer les preuves|प्रमाण पढ्ने|شواہد کی قرأت|Kusoma ushahidi','Conditionals|Phrases conditionnelles|सर्तयुक्त वाक्य|شرطیہ جملے|Sentensi za masharti','Writing explanations|Rédiger une explication|व्याख्या लेख्ने|وضاحتی تحریر|Kuandika ufafanuzi'],
 ['Discussion skills|Compétences de discussion|छलफलका सीप|بحث کی مہارتیں|Ujuzi wa majadiliano','Summarising texts|Résumer des textes|पाठको सारांश|متن کا خلاصہ|Kufupisha maandishi','Reported speech|Discours rapporté|अप्रत्यक्ष कथन|بالواسطہ کلام|Usemi wa taarifa','Writing arguments|Rédiger une argumentation|तर्क लेख्ने|دلائل لکھنا|Kuandika hoja'],
 ['Presentations|Présentations orales|प्रस्तुति|پیشکشیں|Mawasilisho','Analysing narrative|Analyser un récit|कथाको विश्लेषण|بیانیے کا تجزیہ|Kuchambua masimulizi','Grammar and style|Grammaire et style|व्याकरण र शैली|قواعد اور اسلوب|Sarufi na mtindo','Structured essays|Dissertations structurées|संरचित निबन्ध|منظم مضامین|Insha zenye mpangilio'],
 ['Listening and note-taking|Écouter et prendre des notes|सुन्ने र टिपोट|سننا اور نوٹ لینا|Kusikiliza na kunukuu','Analysing information|Analyser l’information|सूचना विश्लेषण|معلومات کا تجزیہ|Kuchambua taarifa','Language and tone|Langue et ton|भाषा र भाव|زبان اور لہجہ|Lugha na toni','Evidence-based writing|Écrire à partir de preuves|प्रमाणमा आधारित लेखन|شواہد پر مبنی تحریر|Uandishi unaotegemea ushahidi'],
 ['Formal communication|Communication formelle|औपचारिक सञ्चार|رسمی ابلاغ|Mawasiliano rasmi','Comparing texts|Comparer des textes|पाठको तुलना|متون کا موازنہ|Kulinganisha matini','Rhetorical choices|Choix rhétoriques|अभिव्यक्तिका छनोट|بلاغی انتخاب|Uchaguzi wa mbinu za usemi','Research summaries|Synthèses de recherche|अनुसन्धान सारांश|تحقیقی خلاصے|Muhtasari wa utafiti'],
 ['Academic discussion|Discussion académique|शैक्षिक छलफल|علمی گفتگو|Majadiliano ya kitaaluma','Critical reading|Lecture critique|समालोचनात्मक पठन|تنقیدی مطالعہ|Usomaji wa uhakiki','Editing for clarity|Réviser pour clarifier|स्पष्टताका लागि सम्पादन|وضاحت کے لیے تدوین|Kuhariri kwa uwazi','Extended writing|Rédaction longue|विस्तृत लेखन|مفصل تحریر|Uandishi mpana']
],
'world-history':[
 ['Sources and timelines|Sources et chronologies|स्रोत र समयरेखा|ماخذ اور زمانی خاکے|Vyanzo na mistari ya wakati','Early cities and rivers|Premières villes et fleuves|प्रारम्भिक सहर र नदी|ابتدائی شہر اور دریا|Miji ya awali na mito','Ancient societies|Sociétés antiques|प्राचीन समाज|قدیم معاشرے|Jamii za kale','Trade and communication|Commerce et communication|व्यापार र सञ्चार|تجارت اور ابلاغ|Biashara na mawasiliano'],
 ['Medieval societies|Sociétés médiévales|मध्यकालीन समाज|قرون وسطیٰ کے معاشرے|Jamii za zama za kati','African kingdoms|Royaumes africains|अफ्रिकी राज्य|افریقی سلطنتیں|Falme za Afrika','Asian trade networks|Réseaux commerciaux asiatiques|एसियाली व्यापार सञ्जाल|ایشیائی تجارتی روابط|Mitandao ya biashara ya Asia','Knowledge and cultural exchange|Savoirs et échanges culturels|ज्ञान र सांस्कृतिक आदानप्रदान|علم اور ثقافتی تبادلہ|Maarifa na mabadilishano ya kitamaduni'],
 ['Oceanic connections|Connexions océaniques|समुद्री सम्पर्क|سمندری روابط|Mahusiano ya baharini','Empires and encounters|Empires et rencontres|साम्राज्य र सम्पर्क|سلطنتیں اور ملاقاتیں|Himaya na makutano','Ideas and institutions|Idées et institutions|विचार र संस्था|خیالات اور ادارے|Mawazo na taasisi','Trade and forced labour|Commerce et travail forcé|व्यापार र बाध्य श्रम|تجارت اور جبری مشقت|Biashara na kazi ya kulazimishwa'],
 ['Revolutions and reform|Révolutions et réformes|क्रान्ति र सुधार|انقلابات اور اصلاحات|Mapinduzi na mageuzi','Industrialisation|Industrialisation|औद्योगिकीकरण|صنعت کاری|Ukuaji wa viwanda','Colonialism and resistance|Colonialisme et résistances|उपनिवेशवाद र प्रतिरोध|نوآبادیات اور مزاحمت|Ukoloni na upinzani','Migration and urban life|Migrations et vie urbaine|बसाइँसराइ र सहरी जीवन|نقل مکانی اور شہری زندگی|Uhamiaji na maisha ya mijini'],
 ['World wars and their causes|Guerres mondiales et causes|विश्वयुद्ध र तिनका कारण|عالمی جنگیں اور ان کے اسباب|Vita vya dunia na sababu zake','Decolonisation|Décolonisation|उपनिवेशमुक्ति|نوآبادیاتی آزادی|Kuondoa ukoloni','International institutions|Institutions internationales|अन्तर्राष्ट्रिय संस्था|بین الاقوامی ادارے|Taasisi za kimataifa','Social and economic change|Changements sociaux et économiques|सामाजिक र आर्थिक परिवर्तन|سماجی اور معاشی تبدیلی|Mabadiliko ya kijamii na kiuchumi'],
 ['The Cold War|La guerre froide|शीतयुद्ध|سرد جنگ|Vita Baridi','Global interdependence|Interdépendance mondiale|विश्वव्यापी अन्तरनिर्भरता|عالمی باہمی انحصار|Kutegemeana duniani','Technology and society|Technologie et société|प्रविधि र समाज|ٹیکنالوجی اور معاشرہ|Teknolojia na jamii','Historical investigation|Enquête historique|ऐतिहासिक अनुसन्धान|تاریخی تحقیق|Uchunguzi wa kihistoria']
]};
export const COURSES=Object.entries(rows).flatMap(([subject,grades])=>grades.map((units,i)=>({subject,grade:i+(subject==='world-history'?7:1),units:units.map((name,j)=>({id:`${subject}-g${i+(subject==='world-history'?7:1)}-u${j+1}`,title:titles(name)}))})));
export function getCourse(subject,grade){return COURSES.find(c=>c.subject===subject&&c.grade===Number(grade));}
export function getUnit(id){for(const c of COURSES){const u=c.units.find(u=>u.id===id);if(u)return {...u,subject:c.subject,grade:c.grade};}return null;}
export const OPTIONAL=['local-history','local-society','local-language','art','music'];
