import {readFileSync,writeFileSync} from 'node:fs';
import {GED_COURSES,GED_LEVELS,GED_SUBJECTS,GED_NOTICE,GED_DESCRIPTION} from '../lib/ged-courses.js';
const configs=Object.fromEntries(Object.entries(GED_COURSES).map(([id,c])=>[id,{title:c.title,subject:c.subject,grade:c.grade,ged:true,voice:false,spokenReview:true,entrance:'/class.html#ged-'+c.level,greeting:GED_NOTICE+'\n'+GED_DESCRIPTION+'\n“시작”이라고 말하거나 입력하면 새로운 10문제를 만들고 검토합니다. 답은 A~D 또는 1~4번입니다.',placeholder:'시작, 답 또는 질문을 입력하세요'}]));
let learn=readFileSync('learn.html','utf8');const start=learn.indexOf('    for(const [key,name] of Object.entries({korean:');const end=learn.indexOf('\n\n    const requestedCourse',start);
if(start>=0)learn=learn.slice(0,start)+'    /* GED_CONFIGS_START */\n    Object.assign(COURSE_CONFIGS,'+JSON.stringify(configs)+');\n    /* GED_CONFIGS_END */'+learn.slice(end);
else learn=learn.replace(/\/\* GED_CONFIGS_START \*\/[\s\S]*?\/\* GED_CONFIGS_END \*\//,'/* GED_CONFIGS_START */\n    Object.assign(COURSE_CONFIGS,'+JSON.stringify(configs)+');\n    /* GED_CONFIGS_END */');
writeFileSync('learn.html',learn);
const blocks=Object.entries(GED_LEVELS).map(([key,l])=>`        <details id="ged-${key}" class="elementary-grade" style="grid-column:1/-1">\n          <summary>🎓 ${l.name} 검정고시</summary>\n          <p style="font-size:16px;line-height:1.6">${GED_NOTICE}<br>${GED_DESCRIPTION}<br>새 수업: 새 문제 생성·검토 · 이어하기: 저장된 문제 계속 · 10문제 · 3회 도전 · 학습 기록</p>\n          <h3>필수 과목</h3>\n${l.required.map(k=>`          <button class="subject" data-href="/learn.html?course=ged-${key}-${k}">${GED_SUBJECTS[k][0]}</button>`).join('\n')}\n          <h3>선택 과목 · ${l.choose}과목 선택 대비</h3>\n${l.optional.map(k=>`          <button class="subject" data-href="/learn.html?course=ged-${key}-${k}">${GED_SUBJECTS[k][0]}</button>`).join('\n')}\n        </details>`).join('\n');
let home=readFileSync('class.html','utf8');home=home.replace(/        <details id="ged-(?:elementary|high)"[\s\S]*?(?=        <button class="subject suneung-route")/,blocks+'\n');writeFileSync('class.html',home);
